Source/Clients/DotNET/Hosting/ClientBuilder.cs

Added Xml comment

---

Source/Clients/AspNetCore/ServiceCollectionExtensions.cs
Source/Clients/AspNetCore/WebApplicationBuilderExtensions.cs

- Added missing service collection extensions for Cratis Workbench

Adding service collection extensions

---

Samples/AspNetCore/Program.cs
Samples/AspNetCore/Startup.cs
Source/Clients/AspNetCore/ApplicationBuilderExtensions.cs
Source/Clients/AspNetCore/AspNetCore.csproj
Source/Fundamentals/Types/Types.cs

- Type discovery for Cratis internals.
- Deep linking fixed - SPA middleware.
- Embedded resources relative path inclusion.

Including Cratis internals for type discovery

---

Source/Clients/AspNetCore/AspNetCore.csproj

- Getting the Workbench actually embedded (Famous last words).

Change to CreateItem for EmbeddedResource

---

Source/Clients/AspNetCore/AspNetCore.csproj

- Disabling workbench build + copying - hoping embedding will finally work.

Disabling workbench build - assuming GH workflow for now

---

Source/Clients/AspNetCore/ApplicationBuilderExtensions.cs

- Dolittle extensions for APIs used by Workbench
- Event Workbench supporting event types with schemas
- Consolidated projects into one Fundamentals project - no need to separate these out, improves build times and general happiness :)

Trigger release

---

Source/Workbench/Events/Web/tsconfig.json

- Dolittle extensions for APIs used by Workbench
- Event Workbench supporting event types with schemas
- Consolidated projects into one Fundamentals project - no need to separate these out, improves build times and general happiness :)

Fixing casing for project reference

---

Samples/Dolittle/Startup.cs
Source/Extensions/Dolittle/Schemas/ApplicationBuilderExtensions.cs
Source/Extensions/Dolittle/Schemas/ServiceCollectionExtensions.cs

- Configuration methods for Dolittle Schema Store

Adding extension methods for configuring Dolittle Schemastore

---

Samples/AspNetCore/Startup.cs
Samples/Dolittle/Startup.cs
Source/Clients/AspNetCore.Workbench/ApplicationBuilderExtensions.cs
Source/Extensions/Dolittle/Schemas/ApplicationBuilderExtensions.cs

- Completely mixed up Use* and Add* for configuration APIs. Fixing this for Dolittle + Workbench setup.

Change from Add* to Use* for Workbench - completely mixed up

---

Samples/Dolittle/Startup.cs
Source/Clients/AspNetCore.Workbench/ServiceCollectionExtensions.cs
Source/Clients/AspNetCore.Workbench/WebApplicationBuilderExtensions.cs
Source/Clients/AspNetCore.Workbench/WorkbenchBuilder.cs
Source/Extensions/Dolittle/Dolittle.csproj
Source/Extensions/Dolittle/WorkbenchBuilderExtensions.cs

- Added builder for workbench for setting assembly that holds the API.
- Added extension method for the Dolittle Workbench API configuration.

Adding builder for configuring workbench

---

Source/Node/FluentUI/package.json
Source/Node/Fundamentals/package.json
Source/Node/React/package.json
Source/Node/TypeScript/package.json
Source/Tooling/Desktop/package.json

- Making sure all package.json files for packages that should be public has a publish profile of such.

Make all packages that should be public; actually public

---

Source/Tooling/Desktop/package.json

- Removing private field from desktop package.

Remove private field

---

Source/Node/FluentUI/package.json
Source/Node/Fundamentals/package.json
Source/Node/React/package.json
Source/Node/TypeScript/package.json
Source/Node/WebPack/package.json
Source/Tooling/Desktop/package.json

Reverting versions to be able to release

---

Samples/Dolittle/DebitAccountProjection.cs
Samples/Dolittle/EventGenerator.cs
Source/Clients/DotNET/Events/Projections/FromBuilder.cs
Source/Clients/DotNET/Events/Projections/FromDefinition.cs
Source/Clients/DotNET/Events/Projections/IFromBuilder.cs
Source/Clients/DotNET/Events/Projections/IPropertyExpressionBuilder.cs
Source/Clients/DotNET/Events/Projections/ISetBuilder.cs
Source/Clients/DotNET/Events/Projections/SetBuilder.cs
Source/Kernel/Events.Projections/Json/JsonProjectionParser.cs
Source/Kernel/Events.Projections/MongoDB/MongoDBProjectionStorage.cs
Source/Kernel/Events.Projections/PropertyMappers.cs
Source/Kernel/Events.Projections/definition-goal.md

- Making the projection API a bit more flexible with regards to building set operations.
- One can now map properties to the event source id.

Projection-mapping-improvements

---

Source/Kernel/Events.Projections.Api/Projections.cs
Source/Kernel/Events.Projections/IProjectionPipeline.cs
Source/Kernel/Events.Projections/IProjections.cs
Source/Kernel/Events.Projections/ProjectionPipeline.cs
Source/Kernel/Events.Projections/Projections.cs

- Workbench will now reflect changes to projections in "real-time" - basically observing what is happening with projections running.

Projection-definitions

---

.github/workflows/publish.yml
run-task-on-workspaces.js

- GitHub Actions failed for publishing due to `package.json` files being altered during build for correct versions. Added a `git reset` task before to the `docker build`.

Fix-docker-release

---

.github/workflows/publish.yml

Adding --hard to git reset

---

Source/Clients/clients.sln

This is primarily a maintenance and cleanup of code release. The reason for the major bump in version is the change in behavior as to where the Compliance workbench is now located and how it is merged with Events to provide a holistic Workbench.
- Merged Compliance and Events workbench for a single workbench frontend.
- Consolidated APIs - cleaning up duplicates.
- Compliance frontfacing APIs are now inside the Kernel.

Fix project paths

---

Directory.Build.props
Source/Kernel/Compliance/Read/Read.csproj

This version is focused on Compliance and specifically GDPR; providing the necessary handling (apply) of events being appended and then for observers and projections (release).
- Compliance applied to events being appended.
- Appended events being released from compliance when rehydrated into observers and projections.
- Encryption keys are stored asymmetrically. This is transparent in the API, but internal behavioral change.
- Kernel mode observers weren't hooked up. We will need to revisit this, see #109.

Logo-duplicate

---

Docker/MongoDB/Dockerfile

- Fixed the path to `entrypoint.sh` in the Dockerfile for our MongoDB image.

Fixing folder for entrypoint

---

Source/ApplicationModel/Tooling/Templates/templates/aspnet/updateAksioReferences.js

- Added `@aksio/cratis-typescript` as package for the template post script for updating references.

Adding @aksio/cratis-typescript as package to also update post create

---

Samples/Bank/Read/Accounts/Debit/DebitAccountObserver.cs
Samples/Bank/Web/Navigation.tsx
Source/ApplicationModel/Frontend/queries/QueryResult.ts
Source/Clients/DotNET/Events/Observation/Observers.cs
Source/Kernel/Store/Shared/EventLogs/EventLogSequenceNumberTokenWithFilter.cs
Source/Workbench/Navigation.tsx

- Minor API documentation errors.
- ExecutionContext not being set for observers in client. It is now hard-coded to Development, as everything else.

Minor-fixes

---

Source/Clients/DotNET/Events/Projections/ChildrenBuilder.cs
Source/Clients/DotNET/Events/Projections/IChildrenBuilder.cs
Source/Clients/DotNET/Events/Projections/IProjectionBuilderFor.cs

- Adding support for Children of Children in projection declarations. The Kernel is prepared for this. 🤞🏻 that this is working as expected.

Children-of-children

---

Source/Clients/DotNET/Events/Projections/ChildrenBuilder.cs
Source/Clients/DotNET/Events/Projections/IChildrenBuilder.cs

- Fixing children model type in expression when building children within children.

Fixing type for children expression

---

Source/Workbench/API/compliance/gdpr/pii/CreateAndRegisterKeyFor.ts
Source/Workbench/API/compliance/gdpr/pii/DeletePIIForPerson.ts
Source/Workbench/API/compliance/microservices/AddMicroservice.ts
Source/Workbench/API/events/projections/Rewind.ts
Source/Workbench/API/events/store/log/Append.ts

- Proxy types for workbench generated with new proxy generator.

New proxies

---

Source/ApplicationModel/Applications/Applications.csproj
Source/ApplicationModel/Applications/Logging/LoggingHostBuilderExtensions.cs
Source/Kernel/Server/Program.cs

- Logging of unhandled exceptions
- Added Serilog.Exceptions and enriching all logs with this to get deeper information about all exceptions.

Logging-exception-details

---

Source/Extensions/MongoDB/MongoDBClientFactory.cs
Source/Extensions/MongoDB/MongoDBClientFactoryLogMessages.cs

- Removing serialization of MongoDB command and exceptions.

Remove serialization of MongoDB command and exceptions

---

Source/Extensions/MongoDB/MongoDBClientFactoryLogMessages.cs

- Removing serialization of MongoDB commands and failures for logging.

Fix parameter

---

.github/workflows/dotnet-build.yml
.github/workflows/node-build.yml
Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs

- Fixing order of precedence for config files (#201)

Fixing Config behavior changed #201

---

Source/Node/TypeScript/package.json
Source/Workbench/package.json

- Fixing order of precedence for config files (#201)

Locking down dependencies

---

Samples/Bank/Read/Accounts/Debit/DebitAccount.cs
Source/ApplicationModel/Tooling/ProxyGenerator/SourceGenerator.cs
Source/ApplicationModel/Tooling/ProxyGenerator/Syntax/TypeSymbolExtensions.cs
Source/ApplicationModel/Tooling/ProxyGenerator/Templates/PropertyDescriptor.cs
Source/ApplicationModel/Tooling/ProxyGenerator/Templates/Type.hbs

- Nullable annotation was in the wrong place for the proxy generator.

Putting nullable in the right place for TS

---

.github/workflows/codetour-watch.yml
.tours/application-model.tour
.tours/logging.tour
.tours/structure.tour

Summary of the PR here. The GitHub release description is created from this comment so keep it nice and descriptive.
Remember to remove sections that you don't need or use.
If it does not make sense to have a summary, you can take that out as well.
- Describe the added features
- Describe the outwards facing code change
- Describe the fix and the bug
- Describe what was removed and why
- Describe the security issue and the fix
- Describe the part of the code being deprecated and why

Started on creating code tours

---

Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs

- When none of the configuration providers can provide values, we now skip. This then makes sure that we don't bind default objects that can't been bound to any configuration data. Concretely fixes a crash we have for clients right now.

If no providers can provide any values, skip

---

Source/Node/WebPack/frontend/rules.js
Source/Node/WebPack/package.json

- Fixed issues with creating and updating module.scss.ts.d-files (Issue #411)
- Add typings for css modules loader to common WebPack config (Issue #412)

Fix webpack issues

---

Source/ApplicationModel/Frontend/package.json

- Fixing dependency versioning for our TypeScript package.

Adding ignoring of warnings for publish ready to run

---

Source/Kernel/Server/TelemetryConfigurationExtensions.cs

- Adding support for Application Insights for Serilog logging
- Adding support for Application Insights telemetry for Orleans from config

Fixing formatting

---

.github/workflows/publish.yml

Adding QEMU to all Docker build jobs

---

.github/workflows/publish.yml

Adding code checkout for all Docker image build jobs

---

.github/workflows/publish.yml

Add workbench cache

---

.github/workflows/publish.yml

- CI/CD pipeline didn't publish

Switching name of variable

---

.github/workflows/publish.yml

- Conditionals for jobs in CI/CD workflow was wrong. Hoping this will actually publish things now.

Fixing Conditional for jobs

---

.github/workflows/publish.yml

- 🤞🏻 CI/CD had job conditionals using true instead of 'true' for whether or not to publish.

Checking for 'true' instead of true. String literal.

---

.github/workflows/publish.yml
.vscode/settings.json
Source/ApplicationModel/Applications/HostBuilderExtensions.cs

- `appsettings.json` can be placed in `./config` folder, adding it to search for the application model.

Appsettings-config

---

.github/workflows/publish.yml

- Adding NPM_AUTH_TOKEN to NPM publish package step in publish-packages job of our CI/CD.

Adding NPM_AUTH_TOKEN

---

.github/workflows/publish.yml

- Fixing cache keys for the data used for transfer between jobs, so that we actually get the artifacts built.

Fixing cache keys

---

.github/workflows/base-development.yml

- Introducing a base development Docker image to improve build times dramatically.

Making release its own job

---

Source/ApplicationModel/Tooling/ProxyGenerator/SourceGenerator.cs

- Supporting nullable properties. When one has an enum that is marked as a nullable in a type, it does not have the type itself annotated as nullable, but the property.

Adding support for properties that gets marked as nullable

---

Documentation/mui/index.md
Documentation/mui/modal.md
Documentation/mui/toc.yml
Documentation/toc.yml
Source/Node/MUI/Modals/Modal.tsx
Source/Node/MUI/Modals/ModalContext.tsx
Source/Node/MUI/Modals/index.ts
Source/Node/MUI/Modals/useModal.ts
Source/Node/MUI/for_RemoveMeSpec/when_actual_spec_added.ts
Source/Node/MUI/index.ts
Source/Node/MUI/package.json
Source/Node/MUI/tsconfig.json

- MUI package with utilities when working with MUI/Material. Currently only has an encapsulation for modals. See docs for more details.

Introducing MUI package with Modal support for now

---

Docker/BaseDevelopment/Dockerfile

- Adding the missing MongoDB Database Tools to the base development image.

Setting correct architecture

---

Docker/BaseDevelopment/Dockerfile

- Adding the missing MongoDB Tools.

Making MongoDB Tools work

---

Docker/BaseDevelopment/Dockerfile

- Adding MongoDB Tools to the base development image.

Actually installing MongoDB tools (I'm a tool)

---

Source/Fundamentals/Json/ExpandoObjectConverter.cs
Source/Fundamentals/Json/JsonValueExtensions.cs
Specifications/Fundamentals/Json/for_ExpandoObjectConverter/OtherType.cs
Specifications/Fundamentals/Json/for_ExpandoObjectConverter/TargetType.cs
Specifications/Fundamentals/Json/for_ExpandoObjectConverter/given/an_expando_object_converter.cs
Specifications/Fundamentals/Json/for_ExpandoObjectConverter/when_converting_complex_structure_to_expando_object.cs
Specifications/Fundamentals/Json/for_ExpandoObjectConverter/when_converting_complex_structure_to_json_object.cs

- Fixed `ExpandoObjectConverter` for edge case value conversions for double <-> float and also for different date & time types.

Specs and fixes as a consequence of getting these

---

.github/workflows/mongodb.yml
Docker/MongoDB/Dockerfile

- Fixing Dockerfile for the development MongoDB image and adding a pipeline to build and deploy it to Docker Hub. (#603)

Creating a pipeline for MongoDB image

---

Source/Kernel/Server/StartupLogMessages.cs

Adding XML comment

---

Documentation/application-model/frontend/identity.md
Documentation/application-model/frontend/toc.yml
Samples/Banking/Bank/Main/IdentityDetailsProvider.cs
Samples/Banking/Bank/Web/App.tsx
Samples/Banking/Bank/Web/Home.tsx
Samples/Banking/Bank/Web/Identity.tsx
Samples/Banking/docker-compose.yml
Samples/Banking/identities.json
Samples/Banking/ingress-middleware-config.json
Samples/Banking/nginx.conf
Source/ApplicationModel/Frontend/identity/IIdentityContext.ts
Source/ApplicationModel/Frontend/identity/IdentityProvider.tsx
Source/ApplicationModel/Frontend/identity/index.ts
Source/ApplicationModel/Frontend/identity/useIdentity.ts
Source/ApplicationModel/Frontend/index.ts
Source/ApplicationModel/Frontend/package.json
Source/ApplicationModel/Tooling/Templates/templates/aspnet/Main/IdentityDetailsProvider.cs
Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/App.tsx
Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/Home.tsx
Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/Identity.tsx

- Added frontend support for identity that works in conjunction with the result from the [Aksio ingress middleware](https://github.com/aksio-insurtech/IngressMiddleware).

Implemented identity context and use identity

---

Source/Extensions/Specifications/EventLogForSpecifications.cs
Source/Extensions/Specifications/EventSequenceForSpecifications.cs

- Helpers for Tests/Specifications now includes the `ValidFrom` value added during `Append`.

Making sure we keep valid from correctly for specs as well

---

Source/Clients/DotNET/Clients/ClientApplicationBuilderExtensions.cs
Source/Clients/DotNET/Clients/RestKernelClient.cs
Source/Kernel/Domain/Clients/ConnectedClients.cs
Source/Kernel/Domain/Clients/ConnectionNotFoundForClient.cs
Source/Kernel/Grains.Interfaces/Clients/IConnectedClients.cs
Source/Kernel/Grains/Clients/ConnectedClients.cs
Source/Workbench/API/clients/Connect.ts
Specifications/Clients/DotNET/Clients/for_RestKernelClient/given/KernelClient.cs
Specifications/Clients/DotNET/Clients/for_RestKernelClient/given/a_rest_kernel_client.cs
Specifications/Clients/DotNET/Clients/for_RestKernelClient/when_connected/and_kernel_returns_error.cs

- Fixing connected client state. (#718)
- Changing the dynamics from Client -> Server connectivity, server no longer pings but instead lets the client know if its considering it disconnected through the result.

Fixing client -> server connectivity, letting the client run the flow

---

Source/Kernel/Engines/Projections/Definitions/ProjectionDefinitions.cs

- Fixing projections check for if it has changes to return true if it has changes and not the opposite as it was.

🤦🏼 HasChanges returned oposite - negating

---

Source/Fundamentals/Changes/ObjectsComparer.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_collections_with_different_element_type_on_left_that_have_null_value_in_left_but_values_in_right.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_collections_with_known_element_type_that_have_null_value_in_both_left_and_right.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_collections_with_known_element_type_that_have_null_value_in_left_but_values_in_right.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_unequal_collections_and_different_element_types.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_unequal_collections_and_different_element_types_on_second_value.cs
Specifications/Fundamentals/Changes/for_ObjectsComparer/when_comparing_object_with_unequal_collections_on_second_element.cs

- Null value handling in the `ObjectsComparer` for elements in collections.

Improved null value handling for elements in collections

---

Source/Clients/DotNET/Clients/IClient.cs
Source/Clients/DotNET/Clients/InsideKernelClient.cs
Source/Clients/DotNET/Clients/RestKernelClient.cs
Source/Clients/DotNET/Clients/RestKernelClientLogMessages.cs
Source/Clients/DotNET/EventSequences/EventSequence.cs

- Improved logging from the client with exception stack trace from the kernel
- Improved logging metadata for client calls to kernel

Adding metadata associated with client commands and queries - used for logging purposes

---

Source/ApplicationModel/Applications/Identity/IdentityProviderEndpointExtensions.cs

- Moving the instantiation of the identity provider to a per request level.

Move provider instantiation

---

Source/Kernel/Grains/Observation/Replay.cs
Source/Kernel/Grains/Observation/ReplayLogMessages.cs

- Adding more logging to replaying

Adding more logging to replay

---

Source/Kernel/Grains/EventSequences/Streaming/EventSequenceQueueAdapter.cs

- Fixing a problem where message batches for the event sequence could be queued before the `CreateReceiver` have been called by Orleans, which then causes observers to be faulty at startup.

Making sure receivers exist, as a message batch seems to be possibly queued before the receiver is created.

---

Source/Kernel/Grains/Observation/ObserverSupervisor.Rewinding.cs
Source/Kernel/Grains/Observation/ObserverSupervisorLogMessages.cs

- Adding more logging for observers for easier diagnostics.

Adding more logging

---

Source/Kernel/Grains/Observation/ObserverSupervisorLogMessages.cs

- Adding more logging for observers for easier diagnostics.

Fixing build error

---

Specifications/Clients/DotNET/Clients/for_RestKernelClient/given/KernelConnection.cs
Specifications/Clients/DotNET/Clients/for_RestKernelClient/given/a_rest_kernel_client.cs

Namespace for ClientOptions have changed

---

Source/Clients/DotNET/Observation/ObserversRegistrar.cs
Source/Clients/DotNET/Observation/UnknownObserverType.cs
Source/Clients/DotNET/Observation/UnknownReducerType.cs
Source/Clients/DotNET/Reducers/IReducersRegistrar.cs
Source/Clients/DotNET/Reducers/ReducerDoesNotExist.cs
Source/Clients/DotNET/Reducers/ReducersRegistrar.cs

- Exposing functionality for getting available reducers and also getting a reducer by its Clr type and get a type by the reducer Id.

Adding docker compose to index

---

Source/Kernel/MongoDB/Operations/MongoDBRecommendationStorage.cs

- Removing JSON serialization for request object of recommendations, which caused an error since we now serialize it BsonDocument directly.

Removing JSON serialization of Request

---

Source/Kernel/Read/EventSequences/EventSequence.cs

Fixed release build error

---

Directory.Packages.props

pin System.Text.Json yet again to the latest stable version 8.0.5

pin version to latest stable 8.0.5 (for now)

---

Directory.Packages.props

- Upgrading ApplicationModel to latest.

Upgrading ApplicationModel

---

Directory.Packages.props

- Upgrading Cratis Application Model which had a resource leakage for MongoDB.

Upgrading AppModel

---

Source/Kernel/Setup/ResilientStorageOptions.cs
Source/Kernel/Setup/StorageProviderExtensions.cs

- `OnRetryEventSeverity` to Polly Resilience system. Defaults to `Debug`

Deal with annoying polly logging

---

Source/Kernel/Grains/Observation/Jobs/HandleEventsForPartition.cs

- Handle the case when handling events for partition and there were no events to handle

Try get result in handle events for partition perform step

---

.github/workflows/codeql.yml
.github/workflows/dotnet-build.yml
.github/workflows/publish.yml
.github/workflows/pull-requests.yml

- Fixing .net 8 version being used during build.

Upgrading to .net 8.0.407

---

Source/Kernel/Projections/Pipelines/ChangesetExtensions.cs

- Temporary fix for `ChangesetExtensions` for doing a best effort on `AddPropertiesFrom()` if the `ExpandoObject` is being modified while enumerating it. The underlying problem needs to be fixed with #1763.

Adding a best effort handling of possible concurrent modifications of an expando object while adding properties-

---

Source/Workbench/Embedded/ChronicleWorkbenchOptions.cs
Source/Workbench/Embedded/WebServer.cs
Source/Workbench/Web/index.html
Source/Workbench/Web/vite.config.ts

- Ability to set the base url that will set the value in the `<base href="/">` tag in the `index.html` file served from the embedded workbench.

Adding an option for specifying what the base should be for the index.html from Workbench

---

Source/Workbench/Embedded/WebServer.cs
Source/Workbench/Web/vite.config.ts

- Fixing the way we set the `base` for assets within the `index.html` file served from the Embedded Workbench.

Changing strategy for how we set base - alter the URLs of any script or style

---

Source/Workbench/Embedded/WebServer.cs

- Fixing the rewrite path for Embedded Workbench

Fixing the rewrite path

---

Directory.Packages.props

Updates Cratis ApplicationModel version

Update application model version

---

Source/Workbench/Embedded/WebServer.cs
Source/Workbench/Web/App.tsx
Source/Workbench/Web/index.html

- Simplifying by making a single base path for both API and frontend for the embedded workbench, which is what the backend actually does set up.

Fixing the base path to be the same for API as for frontend and routing

---

Source/Workbench/Web/App.tsx
Source/Workbench/Web/Features/EventStore/EventStore.tsx
Source/Workbench/Web/Features/Home.tsx
Source/Workbench/Web/Utils/useRelativePath.ts

- Fixing navigation issues when using embedded workbench with a base path. It will now honor this throughout.

Fixing all links in workbench to be relative to base path

---

Integration/Orleans.InProcess/for_EventSequence/when_appending/an_event.cs
Source/Clients/XUnit.Integration/OrleansFixture.cs

- Adding methods for creating `HttpClient`on the `ChronicleFixture`

Adding client creation methods, forgot

---

Source/Clients/DotNET/Events/EventStreamType.cs

- Adding missing `EventStreamType` for `AggregateRoot`.

Formalizing EventStreamType for AggregateRoot

---

Directory.Packages.props
Integration/Api/Api.csproj
Integration/DotNET.InProcess/DotNET.InProcess.csproj
Source/Clients/Api/Api.csproj
Source/Clients/AspNetCore.Specs/AspNetCore.Specs.csproj
Source/Clients/DotNET.InProcess/DotNET.InProcess.csproj
Source/Clients/DotNET/DotNET.csproj
Source/Clients/XUnit.Integration/ChronicleInProcessFixture.cs
Source/Clients/XUnit.Integration/ChronicleOutOfProcessFixture.cs

Updates dependency package versions

Update versions and clean up after dependabot
