Source/Clients/AspNetCore/AspNetCore.csproj
- Fixing embedding of the workbench SPA files to be embedded after it has been copied. This broke on Linux builds.
=> Ordering matters - embedd resources after copy is done

.github/workflows/publish.yml, Source/Clients/AspNetCore/AspNetCore.csproj
- Building Workbench in GitHub workflow as a workaround.
=> Working around ordering issue with embedded reources in MSBuild

.github/workflows/publish.yml, Source/Clients/AspNetCore/AspNetCore.csproj
- Index.html for Workbench now has the correct `/events` prefix for all file references.
=> Adding prefix paths for WebPack output

Documentation/fundamentals/types.md, Source/Fundamentals/Types/Types.cs
- One can now include more assemblies for type discovery in addition to the project referenced assemblies.
=> Custom-assembly-prefixes

Source/Fundamentals/Types/Types.cs
- Fixing so that we actually initialize the assemblies prefix filter property before using it.
=> Initializing filter before using it

Samples/AspNetCore/Startup.cs, Samples/Dolittle/Startup.cs, Source/Clients/AspNetCore.Workbench/ServiceCollectionExtensions.cs, Source/Clients/AspNetCore.Workbench/WebApplicationBuilderExtensions.cs, Source/Extensions/Dolittle/Schemas/ServiceCollectionExtensions.cs
- Fixing ServiceCollection extension APIs from version 2.4.0. Instead of `Use*`for the methods, its now `Add*`. Should've been major version, but since this mistake was done 20 minutes ago - no one has consumed it yet :).
=> Changing from Use* to Add* - more common

.github/workflows/publish.yml, Source/Clients/AspNetCore.Workbench/Root.cs
- Fixing build that creates the embedded version of the Events Workbench after restructuring. This got broken in 2.4.0.
=> Fixing embedding of SPA for Events Workbench

Source/Clients/AspNetCore.Workbench/ApplicationBuilderExtensions.cs
- Fixing build that creates the embedded version of the Events Workbench after restructuring. This got broken in 2.4.0.
=> Fixing namespace reference

Samples/Dolittle/Startup.cs, Source/Clients/AspNetCore.Workbench/ApplicationBuilderExtensions.cs, Source/Extensions/Dolittle/Schemas/ApplicationBuilderExtensions.cs, Source/Extensions/MongoDB/MongoDBDefaults.cs
- Fixing a bug where Bson serializer for Guid already exists when we get to setting up how we want it setup. Turns out that the MongoDB driver will configure a bunch of serializers default if you create a MongoClient, if you then do a registration of a serializer after that - its too late. This fix makes sure we do it before.
=> Making sure serializers are registered properly

Source/Node/FluentUI/package.json, Source/Node/Fundamentals/package.json, Source/Node/React/package.json, Source/Node/TypeScript/package.json
- Remove `"private":false`  from all package.json files. This broke NPM publish claiming the packages were private.
=> Removing private field - not needed and tooling breaks

Source/Fundamentals/Types/ITypes.cs, Source/Fundamentals/Types/Types.cs, Source/Node/TypeScript/package.json
- [C#] `ITypes` now have a property called `ProjectReferencedAssemblies` - enabling you to see all project referenced assemblies discovered.
=> Project-referenced-assemblies

Source/Extensions/MongoDB/ConceptSerializer.cs
- Failsafe for the MongoDB serializer of ConceptAs<Guid> - if the Guid is stored as string, we'll try and parse it as a string representation of the Guid.
=> Read as string if the current BsonType is string

Source/Workbench/Events/Web/Exploring/EventHistogram.tsx, Source/Workbench/Events/Web/Exploring/EventLogs.tsx, Source/Workbench/Events/Web/Navigation.tsx, Source/Workbench/Events/Web/Types/EventTypes.tsx, Source/Workbench/Events/Web/package.json, Source/Workbench/Events/Web/useDataFrom.ts
This PR brings in the ability to have children on models based on events.
When using the C# client API you'll find it as this:
```csharp
[Projection("8fdaaf0d-1291-47b7-b661-2eeba340a520")]
public class AccountsOverviewProjection : IProjectionFor<AccountsOverview>
{
public void Define(IProjectionBuilderFor<AccountsOverview> builder)
{
builder
.Children(_ => _.DebitAccounts, _ => _
.IdentifiedBy(_ => _.Id)
.From<DebitAccountOpened>(_ => _
.UsingParentKey(_ => _.Owner)
.Set(_ => _.Name).To(_ => _.Name)));
}
}
```
You model the relationship by telling what is the property on the model that identifies every child, this is to be able to do the correct operation (Add, Remove, Update) on a child. The Event needs to have a property on it that identifies the parent object; the key. As a child …
=> Fixing lint errors

Samples/Dolittle/EventGenerator.cs, Samples/Dolittle/EventLog.cs, Source/Extensions/Dolittle/Dolittle.csproj, Source/Extensions/Dolittle/EventStore/EventMetadata.cs, Source/Extensions/Dolittle/EventTypes.cs, Source/Extensions/Dolittle/Schemas/SchemaStore.cs
- Upgrading to version 11 of the Dolittle SDK - it had some breaking changes that won't affect the exterior from Cratis.
=> Upgrading to v11 of Dolittle SDK

Source/Extensions/Dolittle/EventStore/EventStore.cs, Source/Extensions/Dolittle/EventStore/EventStream.cs, Source/Extensions/Dolittle/EventStore/EventStreamId.cs, Source/Extensions/Dolittle/EventStore/EventStreamLogMessages.cs, Source/Extensions/Dolittle/EventStore/IEventStore.cs, Source/Extensions/Dolittle/EventStore/IEventStream.cs, Source/Extensions/Dolittle/Projections/ProjectionEventProvider.cs, Source/Extensions/Dolittle/Projections/ProjectionEventProviderLogMessages.cs, Source/Extensions/Dolittle/Projections/Projections.cs
- Formalized `IEventStore` and `IEventStream` for the Dolittle extension - making it possible to work with these in other scenarios other than the internal projection event provider.
=> Extracted out EventStream queries

Source/Extensions/Dolittle/EventTypes.cs, Source/Extensions/Dolittle/Schemas/TypeIsMissingEventType.cs
- Throw `TypeIsMissingEventType` if trying to get `EventTypeId` from a type not adorned with `[EventType]`.
=> Throw exception if trying to get event type id for type without metadata

Source/Extensions/Dolittle/EventStore/EventStore.cs, Source/Extensions/Dolittle/EventStore/EventStoreLogMessages.cs
- Added trace log messages from the Dolittle EventStore implementation.
=> Adding trace messages for event store mongodb commands

Source/Extensions/Dolittle/EventStore/EventStream.cs
- For the Dolittle EventStream implementation we had a **greater than** on the query for getting from a specific offset rather than **greater than or equal**. Meaning we wouldn't get the first event - ever.
=> Fixing query for offset to be Gte, not just Gt

Source/Extensions/Dolittle/Projections/ProjectionEventProvider.cs
- Fixing so that we save the correct offset for the projection - it needs to be the next event offset it will start processing from.
=> Saved offset needs to be the next event it will start from (1 indexed)

Source/Extensions/Dolittle/Projections/Projections.cs, Source/Kernel/Events.Projections/Json/IJsonProjectionSerializer.cs, Source/Kernel/Events.Projections/Json/JsonProjectionSerializer.cs, Source/Kernel/Events.Projections/MongoDB/MongoDBProjectionDefinitions.cs
- Extracting out the interface for the `JsonProjectionSerializer` - enabling mocking in specs internally and externally for anything leveraging custom pipelines.
=> Introducing an interface defining the projection serializer

Samples/Dolittle/ProjectionTesting.cs, Source/Extensions/Dolittle/Projections/ProjectionEventProvider.cs, Source/Kernel/Events.Projections/IProjection.cs, Source/Kernel/Events.Projections/IProjectionEventProvider.cs, Source/Kernel/Events.Projections/IProjectionPipeline.cs, Source/Kernel/Events.Projections/Projection.cs, Source/Kernel/Events.Projections/ProjectionPipeline.cs, Source/Kernel/Events.Projections/ProjectionPipelineLogMessages.cs, Source/Kernel/Events.Projections/ProjectionState.cs, Specifications/Kernel/Events.Projections/for_ProjectionPipeline/given/all_dependencies.cs, Specifications/Kernel/Events.Projections/for_ProjectionPipeline/when_events_are_provided_and_we_have_two_result_stores.cs
- Suspended state for a projection. Typically if a projection fails for some reason.
- Filter on event types per projection on the subjects created in the pipeline.
- Error handling when providing events.
=> Putting in place some error handling + fixing filtering on handling

Source/Clients/AspNetCore.Workbench/AspNetCore.Workbench.csproj, Source/Fundamentals/Schemas/ReflectionService.cs
- Event Type workbench working again - it was not referenced in the output.
- Generating correct type info for concept types. Showing the underlying type.
=> Fix-concept-types-for-schemas

Docker/Dockerfile
- Setting Yarn timeout in Dockerfile to avoid getting **ESOCKETTIMEDOUT** during Yarn install (as suggested [here](https://github.com/yarnpkg/yarn/issues/8242#issuecomment-661881292). This is till we've upgraded to Yarn 2.0 that should have this fixed.
=> Set a timeout for yarn to get more reliable builds

.github/workflows/publish.yml
- Fixing the publishin pipeline - missing working directory for the NuGet publish step.
=> Setting working dir for NuGet publish

Source/Kernel/Projections/Engine/IProjectionFactory.cs, Source/Kernel/Projections/Engine/ProjectionFactory.cs, Source/Kernel/Projections/Engine/Projections.cs, Specifications/Kernel/Projections/Engine/for_Projections/given/no_projections.cs, Specifications/Kernel/Projections/Engine/for_Projections/when_starting_with_one_definition_unregistered_and_one_registered.cs
Improved consistent behavior for child relationships.
Events that represent something that is related to the same event source id as another event can now be modelled in a projection as a child. 
Take the following:
```csharp
public void Define(IProjectionBuilderFor<Person> builder) => builder
.From<PersonRegistered>(_ => _
.Set(m => m.SocialSecurityNumber).To(e => e.SocialSecurityNumber)
.Set(m => m.FirstName).To(e => e.FirstName)
.Set(m => m.LastName).To(e => e.LastName))
.Children(_ => _.PersonalInformation, c => c
.IdentifiedBy(_ => _.Identifier)
.From<PersonalInformationRegistered>(_ => _
.UsingKey(_ => _.Identifier)
.Set\(m => m.Type).To(e => e.Type)
.Set\(m => m.Value).To(e => e.Value)));
```
With the child definition, it will identify the child uniquely based on the `IdentifiedBy` …
=> Using identified by when parentkey is not used

Source/Extensions/MongoDB/MongoDBDefaults.cs, Source/Kernel/Compliance/Engine/CacheEncryptionKeyStore.cs, Source/Kernel/Server/Program.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/given/a_cache_encryption_key_store.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/when_checking_if_has_for/and_cache_does_not_have_it.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/when_checking_if_has_for/and_cache_has_it.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/when_checking_if_has_for/and_everything_is_empty.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/when_deleting.cs, Specifications/Kernel/Compliance/Engine/for_CacheEncryptionKeyStore/when_saving.cs
- Adding a simple inmemory cache that can sit in front of any other `EncrpyptionKeyStore`. Configured for the MongoDB one in kernel right now.
- Hopefully fixing #112 - needs verification since its not consistently happening.
=> Adding simple cache for keys

.github/workflows/publish.yml, Docker/Development/Dockerfile, Docker/Production/Dockerfile, Docker/Workbench/Dockerfile, Source/Fundamentals/Fundamentals.csproj
- Add missing `ApplicationModel/Frontend` for the Workbench Docker image
- Locking down Newtonsoft JSON version + System.IO.FileSystem.Primitives. NJsonSchema has a dependency to an earlier version of Newtonsoft, causing problems during publish with downgraded references.
- Add **latest** tag for Workbench docker image.
=> Fix-docker-images

Samples/Bank/docker-compose.yml, Source/ApplicationModel/Applications/ApplicationBuilderExtensions.cs, Source/ApplicationModel/Applications/HostBuilderExtensions.cs, Source/ApplicationModel/Applications/HostBuilderExtensionsLogMessages.cs, Source/ApplicationModel/Applications/Logging/LoggingHostBuilderExtensions.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Directory.Build.props, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Main/appsettings.json, Source/ApplicationModel/Tooling/Templates/templates/aspnet/docker-compose.yml, Source/Clients/DotNET/Hosting/ClientBuilder.cs, Source/Clients/DotNET/Hosting/ClientBuilderLogMessages.cs, Source/Clients/DotNET/Hosting/HostBuilderExtensions.cs, Source/Clients/DotNET/Hosting/IClientBuilder.cs, Source/Clients/DotNET/Hosting/MongoDBReadModels.cs, Source/Fundamentals/TimedLogging.cs
- Improved startup time for clients by lazily configuring things as needed. Due to our hosted service for setting up projections and other things, Orleans connections get configured in paralell as a consequence to this.
- Fixing microservice template to have the correct NuGet references.
- Adding MongoDB port to the `docker-compose.yml` for the Sample and also the microservice template
- Adding logging to startup of clients - so we're not kept in the dark on whats going on.
=> Improvements

Samples/Bank/Domain/Accounts/Debit/Accounts.cs, Samples/Bank/Domain/Accounts/Debit/CloseDebitAccount.cs, Samples/Bank/Domain/Accounts/Debit/OpenDebitAccount.cs, Samples/Bank/Events/Accounts/Debit/DebitAccountClosed.cs, Samples/Bank/Read/Accounts/Debit/DebitAccountProjection.cs, Samples/Bank/Web/API/accounts/debit/CloseDebitAccount.ts, Samples/Bank/Web/API/accounts/debit/OpenDebitAccount.ts, Source/Clients/DotNET/Events/Projections/ChildrenBuilder.cs, Source/Clients/DotNET/Events/Projections/IProjectionBuilderFor.cs, Source/Clients/DotNET/Events/Projections/ProjectionBuilderFor.cs, Source/Clients/DotNET/Events/Projections/RemovalAlreadyDefined.cs, Source/Fundamentals/Changes/Changeset.cs, Source/Fundamentals/Changes/IChangeset.cs, Source/Fundamentals/Changes/Removed.cs, Source/Kernel/Projections/Engine/InMemory/InMemoryProjectionResultStore.cs, Source/Kernel/Projections/Engine/ProjectionFactory.cs, Source/Kernel/Projections/MongoDB/MongoDBProjectionResultStore.cs, Source/Kernel/Projections/Shared/Definitions/ProjectionDefinition.cs, Source/Kernel/Projections/Shared/Definitions/RemovedWithDefinition.cs, Source/Workbench/Global.d.ts
Adds support for defining a `RemovedWith<TEvent>()` on the projection builder. This is implemented all the way down and will cause a document in e.g. MongoDB to actually be deleted.
A sample of usage:
```csharp
public class DebitAccountProjection : IProjectionFor<DebitAccount>
{
public ProjectionId Identifier => "d1bb5522-5512-42ce-938a-d176536bb01d";
public void Define(IProjectionBuilderFor<DebitAccount> builder) =>
builder
.From<DebitAccountOpened>(_ => _
.Set(model => model.Name).To(@event => @event.Name)
.Set(model => model.Owner).To(@event => @event.Owner))
.From<DepositToDebitAccountPerformed>(_ => _
.Add(model => model.Balance).With(@event => @event.Amount))
.From<WithdrawalFromDebitAccountPerformed>(_ => _
.Subtract(model => model.Balance).With(@event => @event.Amount))
// ** NEW …
```
=> Adding support for RemovedWith - #134

Source/Fundamentals/Changes/PropertyDifference.cs
- Fixing so that `PropertyDifference` supports concepts - used for now in the integration parts.
=> Reorder to trigger :)

Documentation/application-model/configuration.md, Source/ApplicationModel/Applications/HostBuilderExtensions.cs, Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs, Source/Fundamentals/Configuration/MissingConfiguration.cs
- Adds search paths for config files. By default it adds `$PWD/config` and automatically also `$PWD` as fallback. This is very helpful when packaged and leverages with services like Azure Container Instances which can't mount files, only folders.
=> Adding search paths - to be able to have config files in subfolders

Samples/Bank/Main/Main.csproj, Samples/Bank/Main/appsettings.json, Source/ApplicationModel/Applications/Logging/LoggingHostBuilderExtensions.cs, Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs, Source/Kernel/Server/Server.csproj
- Look for **appsettings.json** in a **config** sub folder, this will help us configure everything when using Azure Container Instances due to its lack of not supporting indivdual file mounts.
- Configured Serilog to self-log, very useful for errors.
- Kernel now has Serilogs Elastic extension added to it.
- Added sample of how to use Serilogs Elastic for production for the Bank sample, which means also for the default template when creating a new Microservice.
=> Elastic-logging

Source/ApplicationModel/Applications/ApplicationBuilderExtensions.cs, Source/ApplicationModel/Applications/HostBuilderExtensions.cs
- All HTTP & HTTPS requests will now have their responses compressed supporting GZip and Brotli, depending on `Accept-Encoding`.
=> Adding GZip and Brotli compression for Web responses

.github/workflows/dotnet-build.yml, .github/workflows/publish.yml, .gitignore, Docker/Development/Dockerfile, Docker/Production/Dockerfile, Docker/Workbench/Dockerfile, Docker/build-server.sh, Docker/copy-server-files.sh, dockerize.sh, global.json
- Publish GitHub Actions workflow was very slow due to the multiple architecture build of the development image. This is now improved by doing the build of the binaries outside of Docker and then just copying these into the image. (#115).
=> Optimizing publish workflow, Fixes #115

.github/workflows/publish.yml
- Removing the MongoDB image build from release workflow. If needed, we should move this to another repository. Right now in development we have the development image with MongoDB in it and configured correctly for single node cluster mode.
=> Changing order of Dev image before Mongo and allowing Mongo to fail

Source/Extensions/MongoDB/MongoDBClientFactory.cs, Source/Extensions/MongoDB/MongoDBClientFactoryLogMessages.cs
- When logging MongoDB commands or failures, Serilog went into stack overflow trying to convert some of the MongoDB specific types. Fixing this by converting to JSON first and then into an object that gets passed into the logger.
=> Fixing logging for MongoDB to avoid Serilog going into a stack overflow

Source/Clients/DotNET/Hosting/MongoDBReadModels.cs
- Aggressive logging for telling which read models are bound for the IoC has now been moved to be only during setup.
=> Move logging for setup out of transient bindng callback

Samples/Bank/Main/appsettings.Elastic.json, Source/Kernel/Compliance/Engine/JsonComplianceManager.cs, Source/Kernel/Server/appsettings.Development.json, Source/Kernel/Server/appsettings.json
- Fixing a bug when recursively applying compliance for events for complex structures. NJsonSchema has properties that are prefixed **Actual** which point to resolved versions for type references.
=> Compliance-manager-fix

Source/Clients/DotNET/Events/Projections/FromBuilder.cs, Source/Clients/DotNET/Events/Projections/SetBuilder.cs
- Client was using the last name of the property when setting up properties for projection causing nested structures in both read models and events to be wrong. This is now fixed and it creates a fully qualified `PropertyPath`.
=> Fixing so that we resolve the entire property path for all projection property operations

Source/Kernel/Compliance/Engine/JsonComplianceManager.cs
- Switching to using `ActualTypeSchema` from NJsonSchema for recursive nested schemas. When properties are considered nullable, NJsonSchema will create a "one-of" with Null and and the actual type. `ActualSchema` does not resolve to the actual type schema.
=> Switching to ActualTypeSchema - it resolves to the correct type schema

Source/Clients/DotNET/Events/Projections/ChildrenBuilder.cs, Source/Clients/DotNET/Events/Projections/ProjectionBuilderFor.cs
- Child relationships are now using PropertyPath for nested objects in the Client definition, not just the name of the last property in the chain.
=> Fixing child relations to use property paths

Source/Clients/DotNET/Hosting/MongoDBReadModels.cs, Specifications/Clients/DotNET/Hosting/for_MongoDBReadModels/when_adding_read_models_with_type_taking_collection.cs, Specifications/Clients/DotNET/Hosting/for_MongoDBReadModels/when_adding_read_models_with_type_taking_provider_for_collection.cs
- Supporting discovery and hookup of bindings for `IMongoCollection<ReadModel>` based on constructors that takes `ProviderFor<IMongoCollection<ReadModel>>`. Delivering parts of whats described in #191.
=> Adding IoC bindings for ProviderFor<> for MongoCollections

Source/Extensions/Orleans/Orleans.csproj
- Configuration of cluster options supporting local, Azure Storage and ADO.NET for now. All done through a new `cluster.json` file. If the file is missing, localhost clustering is assumed for development purposes.
- Adding a way to resolve configuration values that differ in type / implementation. See the docs for more details.
=> Adding explicit version dependency to fix downgrade errors

Source/ApplicationModel/Tooling/ProxyGenerator/Syntax/TypeSymbolExtensions.cs
- Fixed type support in proxy generation. It was using `string` for C# types `DateTime`and `DateTimeOffset`, now it uses `Date`.
=> Add support for Date type for proxy generated types

Source/Fundamentals/Dynamic/ExpandoObjectExtensions.cs, Source/Kernel/Projections/Engine/Projection.cs, Source/Kernel/Projections/Engine/ProjectionFactory.cs, Source/Kernel/Projections/Grains/Projection.cs, Source/Node/FluentUI/package.json, package.json
- Fixing order of precedence for config files (#201).
- Fixing `GetModelInstanceById()`of the Projection Grain to be in line with how the `ProjectionPipelineHandler`handles events. This rises technical debt for later; #205.
=> Fix-adhoc-projection

Source/ApplicationModel/Tooling/ProxyGenerator/Syntax/TypeSymbolExtensions.cs
- Proxy generator now returns the correct underlying type for nullables and not `Nullable`.
=> Returning correct type for nullables

.vscode/settings.json, Samples/Bank/GlobalUsings.Specs.cs, Samples/Bank/Integration.Specs/AccountHolders/for_AccountHolderDetailsAdapter/when_importing_for_the_second_time_without_changes.cs, Source/Extensions/Specifications/AppendedEventForSpecifications.cs, Source/Extensions/Specifications/EventLogForSpecifications.cs, Source/Extensions/Specifications/EventSequenceStorageProviderForSpecifications.cs, Source/Extensions/Specifications/IHaveEventLog.cs, Source/Extensions/Specifications/Integration/AdapterSpecificationContext.cs, Source/Extensions/Specifications/Integration/ShouldEventLogExtensions.cs, Source/Extensions/Specifications/Projections/ProjectionSpecificationContext.cs
- For asserting if that events are not added during import one should now use `ShouldNotAppendEventsDuringImport()`.
- More flexibility around how to write custom assertions. `IHaveEventLog` is an interface implemented by `AdpaterSpecificationContext<,>` and `ProjectionSpecificationContext<>` holding the actual appended events. (Fixes #297)
- Moved assertions into general extension methods that can be used for anything implementing `IHaveEventLog`.
=> Event-spec-api-fixes

Source/Kernel/Server/ClusterConfigurationExtensions.cs
- Added support for specifying the silos hostname in the cluster configuration. When this is specified, it ignore the `AdvertisedIP` configuration.
=> Fixing typo in hostName - should be hostname

Documentation/fundamentals/configuration.md, Source/Clients/DotNET/Orleans/ClusterConfigurationExtensions.cs, Source/Extensions/Orleans/Configuration/AdoNetClusterOptions.cs, Source/Extensions/Orleans/Configuration/AzureStorageClusterOptions.cs, Source/Extensions/Orleans/Configuration/ClusterConfigurationExtensions.cs, Source/Extensions/Orleans/Configuration/ClusterOptionsValueResolver.cs, Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs, Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensionsLogMessages.cs, Source/Kernel/Server/ClusterConfigurationExtensions.cs
- Switching from using Orleans options types for cluster configuration to our own (Azure Storage and Ado Net). (Fixes #303).
=> Azure-storage-options-fix

Docker/Production/Dockerfile
- Production image in 6.1.9 is broken due to missing `.deps.json` files. These are now braught back and `cratis.json` which was the file we intended to remove is now explicitly removed from the image.
=> Putting back all .deps.json files and just leaving cratis.json out

Documentation/fundamentals/concepts.md, Source/Fundamentals/Concepts/ConceptFactory.cs, Specifications/Fundamentals/Concepts/for_ConceptFactory/DateTimeOffsetConcept.cs, Specifications/Fundamentals/Concepts/for_ConceptFactory/when_creating_instance_of_datetime_concept_with_value_as_string.cs, Specifications/Fundamentals/Concepts/for_ConceptFactory/when_creating_instance_of_datetimeoffset_concept_with_value_as_datetime.cs, Specifications/Fundamentals/Concepts/for_ConceptFactory/when_creating_instance_of_datetimeoffset_concept_with_value_as_string.cs
- `ConceptFactory` now supports conversion from a string representation to `DateTimeOffset`. .NET does not support type conversion of this when using `Convert.ChangeType()`.
- Updated [documentation for concepts](./Documentation/fundamentals/concepts.md) regarding them representing a single value.
=> Fixing a problem regarding parsing of DateTimeOffset

Samples/Banking/Bank/Web/Home.tsx
- Add missing information about the projects that is in the sample and gets created from the template.
=> Add missing information on the landing page

Source/Kernel/Store/Api/EventSequence.cs, Source/Workbench/events/store/EventSequences.tsx, Source/Workbench/events/store/Observers.tsx
- The Kernel REST API now honors the EventSequenceId in the `FindFor` query.
- Event sequence view in Workbench now refreshes the event types when selecting a microservice.
- Showing correct type for Inbox observer type in observer view.
=> Workbench-fixes

Source/Kernel/Store/Grains/EventSequence.cs
- Fixing an exception when appending events saying "Execution context not set", which was caused by the dependency `JsonComplianceManager` changed in scope and setup with new registrations.
=> Use ProviderFor<> for JsonComplianceManager to get it in the correct context

Source/ApplicationModel/Tooling/ProxyGenerator/SourceGenerator.cs
- Fixes a problem where the proxy generator didn't include relative path information for imports when the path was a parent path.
=> Fixing support for relative path include for proxies

Documentation/fundamentals/types.md, Source/Fundamentals/Types/Types.cs
- Kernel didn't start in docker due to it trying to explicitly load assemblies starting with `runtimepack`.
=> Assembly-exclusion

Samples/Banking/Bank/Main/Program.cs, Samples/Banking/Bank/cratis.json, Samples/Banking/cratis.json, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Main/Program.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/cratis.json, Source/Kernel/Server/cratis.json
- Changing to Bank microservice having the `Guid.Empty()` identifier. Since this is the default identifier if none is specified, the Kernel will work for all that has this not set. In a future version we will don't care about this type of configuration and let the connecting client tell which Microservice it is.
=> Setting default MS for now to Guid.Empty

Source/ApplicationModel/Tooling/Templates/templates/aspnet/Directory.Build.props
- FIxing Aksio Microservice template to build the specs projects. Missing XUnit reference and was using project reference instead of package reference for the specifications extensions.
=> Fixing so that the specs projects build in the template

Source/ApplicationModel/Tooling/ProxyGenerator/Templates/ImportStatement.cs, Source/Kernel/Store/Shared/EventContext.cs
- Adding convenience methods for `EventContext`. (#398)
- Fixes import paths to be correct across platforms. (#395)
=> Forcing forward slash for import statements

Source/Kernel/Store/Shared/EventContext.cs
- Messed up the API in 6.7.0 for `EventContext.Empty()` should've been `EventContext.Empty`.
=> Fixing empty to not be a method but a static field

Source/Node/WebPack/frontend/index.js
- Added cache to development to decrease startup time. (#403)
=> 403-add-cache-setup-to-webpack-config

Documentation/fundamentals/configuration.md, Source/Fundamentals/Configuration/ConfigurationHostBuilderExtensions.cs, Source/Fundamentals/Configuration/IPerformPostBindOperations.cs, Source/Kernel/Configuration/Shared/KernelConfiguration.cs, Source/Kernel/Configuration/Shared/Storage.cs
Adding support for performing operations after the config objects values has been bound up.
Automatically recognized. Below is a sample, read more in the documentation:
```csharp
[Configuration("MyConfig")]
public class ConfigObject : IPerformPostBindOperations
{
public void Perform()
{
// Perform a post bind operation
}
}
```
- Configuration objects can now implement `IPerformPostBindOperations` to be called after values have been bound to it.
=> Adding support for post bind operations

DocFX/package.json
- React upgraded to version 18.0
- Upgraded all NuGet dependencies to latest
- Latest version of .NET for build actions
=> Making DocFX private

Source/Node/WebPack/frontend/rules.js
- Removing CSS rule from WebPack setup, with the SASS rule we seem to be picking up CSS as well.
=> Removing explicit css loader as the sass loader seems to work fine

Source/Kernel/Configuration/Shared/KernelConfiguration.cs
- Adding the `Telemetry` configration object to the Cratis Kernel configuration object.
=> Adding telemetry config to the Cratis Kernel config

Source/ApplicationModel/Frontend/queries/useObservableQuery.ts, Source/ApplicationModel/Frontend/queries/useQuery.ts
- Converting to `any` for query arguments when passed down to base type for `useQuery()` and `useObservableQuery()` hooks.
=> Fixing type conversion for query args

.github/workflows/publish.yml
- Path to x64 cache used between jobs in CI/CD.
=> Fixing x64 cache path

Source/Kernel/Projections/Grains/ImmediateProjection.cs
- Immediate projections now set the `Id` property to the `modelKey` being  asked for. A future expansion on this will be to allow defininig which property is the `Id` property (#455)
=> Making sure we set Id by default for the return of immediate projections

Source/ApplicationModel/Applications/HostBuilderExtensions.cs
- `appsettings.json` can be placed in `./config` folder, adding it to search for the application model.
=> Fixing whitespace

.github/workflows/publish.yml
- Fixing publish-packages job of CI/CD with regards to the cache folder for node_modules++
=> Setting folder for yarn cache for publishing packages

.dockerignore
- Taking out `appsettings.json` from the built Docker images. One needs now to configure this and mount it in for logging and other things.
=> Ignore app settings

Directory.Build.props, Versions.props
- Including PDB debug symbols and source in packages. Also adding source link. This to be able to debug broadly in different tooling. Downside is of course that the packages will become much larger. We'll keep an eye on this and change if necessary. Our complete setup now includes generation of `.snupkg`, include PDB files, include source in packages and source link.
=> Adding debug info to packages + source link

Versions.props
- Reverting the inclusion of PDB files. Relying on source link and .snupkg.
=> Using latest Aksio.Defaults

Source/Kernel/Projections/Engine/Projection.cs, Source/Kernel/Projections/Engine/ProjectionExtensions.cs, Specifications/Kernel/Projections/Engine/for_Projection/given/a_projection.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_getting_key_resolver_for_event_type.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_getting_key_resolver_for_event_type_registered_as_public.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_getting_key_resolver_for_unknown_event_type.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_next_event_is_a_public_event.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_next_event_is_not_of_interest.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_next_event_is_of_interest.cs, Specifications/Kernel/Projections/Engine/for_ProjectionExtensions/when_applying_from_filter/and_issuing_public_event_with_type_that_is_included.cs, Specifications/Kernel/Projections/Engine/for_ProjectionExtensions/when_handling_remove_with_public_event.cs
- Projections are now only looking at the event type identifier and ignoring generation and whether or not it is public when filtering event types it is interested in.
=> Ignoring the IsPublic part of event type when filtering events we're interested in

Source/Extensions/Specifications/EventSequenceStorageProviderForSpecifications.cs
- Fixing so that automated tests/specifications for projections just looks at the event type identifier and ignores the public flag when filtering. As the rest of the system does.
=> Fixing event type filtering

Source/Kernel/Projections/Engine/Projection.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_asking_if_private_event_type_is_accepted_and_it_is_registered_as_private.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_asking_if_public_event_type_is_accepted_and_it_is_registered_as_private.cs, Specifications/Kernel/Projections/Engine/for_Projection/when_asking_if_unknown_event_type_is_accepted.cs
- Making projections accept event types based only on their identifier, ignoring generation and whether or not it is marked public.
=> Making projections accept event types based on identifier

Source/Kernel/Schemas/MongoDB/MissingEventSchemaForEventType.cs, Source/Kernel/Schemas/MongoDB/MongoDBSchemaStore.cs
- Making it clearer when an event type is missing from the event schema store by throwing an explicit exception.
=> Add an explicit exception when an event type is missing from schema store

Source/Extensions/MongoDB/DateOnlySerializer.cs
- Fixing `DateOnlySerializer` to use mid-day point for time component when serializing to Bson Date. Without it, the date will slide a day per serialization due to timezones.
=> Setting Time component to mid-day to avoid date sliding during serialization

Docker/BaseDevelopment/Dockerfile
- Changing the base image to the ASP.NET Core runtime for the base development image.
=> Change to ASPNET as base image

Source/Kernel/Compliance/Domain/Domain.csproj, Source/Kernel/Compliance/Read/Read.csproj, Source/Kernel/Configuration/Api/Api.csproj, Source/Kernel/Directory.Build.props, Source/Kernel/Projections/Api/Api.csproj, Source/Kernel/ProxyGeneration.props, Source/Kernel/Schemas/Api/Api.csproj, Source/Kernel/Store/Api/Api.csproj
- Removing reference to the proxy generator for all assemblies related to Kernel and just add it to the API projects. This way we're not pulling the proxy generator implicitly into everything when referencing the C# SDK. (Plus added benefit of faster Cratis compile times :))
=> Taking ProxyGenerator out as a cross cutting thing and adding it explicitly into the projects that need it

.github/workflows/publish.yml
- Fixing publish pipeline after breaking into NuGet and NPM package jobs. Adding the needed checkout for the NPM job.
=> Adding checkout

Source/ApplicationModel/Tooling/ProxyGenerator/SourceGenerator.cs
- Removing debugger statement in proxy generator that was left in while hunting down a problem.
=> Removing debugger statement left in while debugging

Source/ApplicationModel/Frontend/queries/QueryResult.ts
- `JsonSerializer` was referenced wrongly within `DerivedType`.
=> Reference JsonSerializer through root index

Source/ApplicationModel/Frontend/commands/Command.ts
- Due to #359 the frontend does not get a valid JSON on 200 OK responses. This is now taken into account and it will return a valid command result if this happens.
=> If not possible to parse JSON, return empty command result

Samples/Banking/Bank/Read/Accounts/Debit/DebitAccountProjection.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Domain/Customers/Customers.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Read.Specs/Accounts/Debit/for_DebitAccountProjection/when_opening_account.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Read/AccountHolders/AccountHolderWithAccountsObserver.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Read/Accounts/Debit/DebitAccountProjection.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/Owner.ts, Source/Clients/DotNET/Events/Projections/AllBuilder.cs, Source/Clients/DotNET/Events/Projections/AllSetBuilder.cs, Source/Clients/DotNET/Events/Projections/ChildrenBuilder.cs, Source/Clients/DotNET/Events/Projections/IAllBuilder.cs, Source/Clients/DotNET/Events/Projections/IAllSetBuilder.cs, Source/Clients/DotNET/Events/Projections/IChildrenBuilder.cs, Source/Clients/DotNET/Events/Projections/IModelPropertiesBuilder.cs, Source/Clients/DotNET/Events/Projections/IProjectionBuilderFor.cs, Source/Clients/DotNET/Events/Projections/MissingToExpressionForAllSet.cs, Source/Clients/DotNET/Events/Projections/ProjectionBuilderFor.cs, Source/Kernel/Projections/Engine/ProjectionFactory.cs, Source/Kernel/Projections/Shared/Definitions/AllDefinition.cs, Source/Kernel/Projections/Shared/Definitions/ChildrenDefinition.cs, Source/Kernel/Projections/Shared/Definitions/ProjectionDefinition.cs
- Adding the ability to project to model properties from properties from the event context from all events in a projection. Useful when one wants to set something like `LastUpdated` date time and base it on the `Occurred`.
```csharp
public class DebitAccountProjection : IProjectionFor<DebitAccount>
{
public ProjectionId Identifier => "d1bb5522-5512-42ce-938a-d176536bb01d";
public void Define(IProjectionBuilderFor<DebitAccount> builder) =>
builder
.WithInitialModelState(() => new(Guid.Empty, string.Empty, Guid.Empty, new(string.Empty, string.Empty), 0, false, DateTimeOffset.MinValue))
// Set LastUpdated to Occurred for all events, and include any child projections
.All(_ => _
.Set(model => model.LastUpdated).ToEventContextProperty(ContextBoundObject => ContextBoundObject.Occurred) …
```
=> Up and running with API and definition for All expressions

Docker/BaseDevelopment/Dockerfile
- Adding the missing MongoDB Database Tools to the base development image.
=> Adding MongoDB Database Tools to the base development image

Source/Kernel/Projections/MongoDB/MongoDBProjectionSink.cs
- Making sure we set the correct type based on the model schema for properties in a changeset. This fixes an exception that occurred when Guids were used, as it didn't know how to make them with the correct guid representation for Mongo.
=> Fixing how we set properties - convert to the correct type based on schema target

Source/Extensions/MongoDB/BsonValueExtensions.cs, Source/Extensions/MongoDB/ExpandoObjectConverter.cs, Source/Fundamentals/Json/JsonSchemaExtensions.cs, Source/Kernel/Projections/MongoDB/MongoDBProjectionSink.cs, Source/Kernel/Projections/MongoDB/MongoDBProjectionSinkFactory.cs
- The MongoDB Projection Sink is now much stricter on the models schema and target types and will convert both keys and properties according to the schema.
=> Making the MongoDB sink strict on target type conversion for properties and keys

Source/Extensions/Specifications/EventSequenceStorageProviderForSpecifications.cs, Source/Kernel/Projections/Engine/KeyResolvers.cs, Source/Kernel/Store/MongoDB/MongoDBEventSequenceStorageProvider.cs, Source/Kernel/Store/Shared/IEventSequenceStorageProvider.cs, Specifications/Kernel/Projections/Engine/for_KeyResolvers/when_identifying_model_key_from_parent_hierarchy_with_four_levels.cs, Specifications/Kernel/Projections/Engine/for_KeyResolvers/when_identifying_model_key_from_parent_hierarchy_with_one_level.cs
- Making parent hierarchy key resolution use any of the parents event types, not forcing the first in its definition. The first in the definition might not be the first that gets appended.
=> Parent hierarchy resolution now does not rely on the first event type of the parent, but any of them

Source/Fundamentals/Json/JsonValueExtensions.cs, Source/Kernel/Store/MongoDB/MongoDBEventSequences.cs
- `DateOnly`and `TimeOnly` serialization from `JsonValue` now parses the string if its not a `DateTime` source type.
- Switched to using the `System.Text.Json` serializer when saving the event content in the event log, which then persists `DateOnly`and `TimeOnly` and other types with converters correctly.
=> Fixing so that we create the correct types from Json and to Json for DateOnly and TimeOnly

Source/Kernel/Projections/Grains/ImmediateProjection.cs
- Fixed Immediate projections after internal type safety changes, making sure we can serialize the result properly. It crashed under certain circumstances.
=> Fixing immediate projections after all internal changes

Source/Clients/DotNET/Events/Projections/SetBuilder.cs
- Fixing so that we get the actual enum value as an integer before sending it to the kernel for the `.ToValue()` support till we have implemented #579.
=> Converting enum values to integer till we get #579 done properly

Source/Kernel/Projections/Engine/Expressions/Keys/CompositeKeyExpressionResolver.cs
- Composite key resolver now maintains the correct property path, enabling it to resolve to the correct type for the nested properties.
=> Composite keys will now resolve the actual nested properties

Source/ApplicationModel/Tooling/Templates/templates/aspnet/Concepts/Accounts/DebitAccountCloseReason.cs, Source/Kernel/Schemas/MongoDB/MongoDBSchemaStore.cs
- Changing all MongoDB calls for the schema store to be synchronous. To avoid problems with the Orleans task model.
=> Changing all calls to MongoDB to be synchronous

Source/ApplicationModel/Tooling/Templates/templates/aspnet/Concepts/Accounts/DebitAccountCloseReason.cs, Source/Kernel/Store/MongoDB/MongoDBEventSequences.cs
- Fixing so that we get the schema-store using the `ProviderFor<>`. It is singleton per microservice, but we were just injecting it without thinking of the scoping of where it was injected. The consequence of that is that we were getting the wrong schema store every now and then.
=> We were getting the wrong schema store occassionally. Due to scoping issues with the IOC

Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/CloseDebitAccount.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/DepositToAccount.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/OpenDebitAccount.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/SetDebitAccountName.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/Debit/WithdrawFromAccount.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/API/Accounts/credit/OpenCreditAccount.ts, Source/Workbench/API/compliance/gdpr/pii/CreateAndRegisterKeyFor.ts, Source/Workbench/API/compliance/gdpr/pii/DeletePIIForPerson.ts, Source/Workbench/API/compliance/microservices/AddMicroservice.ts, Source/Workbench/API/events/store/observers/Rewind.ts, Source/Workbench/API/events/store/sequence/Append.ts
- `useCommand()` now returns a third component to the tuple; `ClearCommandValues` which sets them all to undefined. The proxy generator honors this and creates a proxy that does the same. (#595)
- Fixing the `SetCommandValues` returned from `useCommand()` to only ignore properties that are either undefined or null. Allowing for empty strings to be set. (#596)
=> Fixing generated proxies

Source/Fundamentals/Types/Types.cs
- Ignoring load failures related to project references assemblies. These assemblies will then not be part of type discovery.
=> Ignoring project referenced assemblies that fail loading

Source/Clients/DotNET/Hosting/ClientBuilder.cs, Source/Clients/DotNET/Hosting/ClientBuilderLogMessages.cs
- Adding a log message to see why the cluster client is not able to connect to Cratis Kernel.
=> Adding log messages to see why client is struggling connecting

Source/Clients/DotNET/Hosting/ClientBuilder.cs, Source/Clients/DotNET/Hosting/ClientBuilderLogMessages.cs
- Adding inner exception to the log message when connection failed to Kernel.
=> Adding inner exception to log message when errored connect

Source/ApplicationModel/CQRS/Queries/QueryActionFilter.cs
In the ASP.NET Core 6 code there is a middleware called WebSocketMiddleware. The WebSocketManager
that we ask for .IsWebSocketRequest forwards this call to it.
This property calls internally a method called CheckSupportedWebSocketRequest which will check
the following Http Headers for valid values:
Upgrade with value Upgrade
Connection with value websocket
If they are correct, it will consider it an upgrade of the protocol and will then validate and use
the values from the Web Socket specific headers:
Sec-WebSocket-Protocol
Sec-WebSocket-Extensions
Sec-WebSocket-Version
Sec-WebSocket-Key
When running in an environment with multiple reverse proxies you can end up with the proxy adding
to the values if the values are already there, forming a collection of values as comma separated
values in …
=> Making sure we have the correct SecWebSocketKey for validation of the upgraded connection

Source/Workbench/API/compliance/gdpr/pii/CreateAndRegisterKeyFor.ts, Source/Workbench/API/compliance/gdpr/pii/DeletePIIForPerson.ts, Source/Workbench/API/compliance/microservices/AddMicroservice.ts, Source/Workbench/API/events/store/observers/Rewind.ts, Source/Workbench/API/events/store/sequence/Append.ts
- Support for returning a response object as part of a command. POST controller actions can simply just return anything now and this will now become serialized as part of the `CommandResult` and proxy generator generates a type safe version of this with serialization information on it. (#499)
- Command result is now alway included, even when it is a HTTP 200. (#359)
=> Regenerated proxies

Source/Fundamentals/Json/EnumerableModelWithIdToConceptOrPrimitiveEnumerableConverter.cs
- JSON Converter for dealing with enumerable of objects with Id or concepts now stops at the end of the array, not trying to consume the rest of the JSON.
=> Stopping at the end of the array

Samples/Banking/Bank/Main/Program.cs, Source/ApplicationModel/CQRS/Commands/CommandActionFilter.cs, Source/ApplicationModel/CQRS/Commands/CommandResult.cs, Source/ApplicationModel/CQRS/Queries/ClientObservable.cs, Source/ApplicationModel/CQRS/Queries/QueryActionFilter.cs, Source/ApplicationModel/CQRS/Queries/QueryResult.cs, Source/ApplicationModel/CQRS/Validation/ValidationError.cs, Source/ApplicationModel/Frontend/queries/IQueryResult.ts, Source/ApplicationModel/Frontend/queries/NullObservableQueryConnection.ts, Source/ApplicationModel/Frontend/queries/QueryFor.ts, Source/ApplicationModel/Frontend/queries/QueryResult.ts, Source/ApplicationModel/Frontend/queries/QueryResultWithState.ts, Source/ApplicationModel/Frontend/queries/useObservableQuery.ts, Source/ApplicationModel/Frontend/queries/useQuery.ts, Source/ApplicationModel/Tooling/ProxyGenerator/Templates/Query.hbs
- Honoring the actual type of the query argument when generating proxies. (#636)
- Forcing invariant culture for Kernel. (#611)
- Returning proper query result structure with all details which then automatically fixed #637
- Returning correct command result even if exceptions happen in controller action.
- Making member names camel cased in validation result. (#593)
=> Getting the actual type of the query argument

Source/ApplicationModel/CQRS/Commands/CommandActionFilter.cs, Source/ApplicationModel/CQRS/Queries/QueryActionFilter.cs, Source/ApplicationModel/Frontend/queries/IQueryResult.ts, Source/ApplicationModel/Frontend/queries/QueryResultWithState.ts, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Main/Program.cs, Source/Kernel/Server/Program.cs
- Honoring the actual type of the query argument when generating proxies. (#636)
- Forcing invariant culture for Kernel. (#611)
- Returning proper query result structure with all details which then automatically fixed #637
- Returning correct command result even if exceptions happen in controller action.
- Making member names camel cased in validation result. (#593)
=> Fixing query results to have the hasData

Samples/Banking/Bank/Web/Home.tsx
- Fixing queries not to execute twice when explicitly executing them via the React hook. (#644)
- Fixing so that we allow arguments in queries that hold 0 for number or false for booleans. (#645)
=> Only consider undefined and null values as not set - allow 0 or false

Source/ApplicationModel/Frontend/queries/QueryResultWithState.ts, Source/ApplicationModel/Frontend/queries/useQuery.ts
- Setting `isPerforming` on query result when using React hook for queries to `true` for the initial state.
=> Setting isPerforming = true as initial state for queries when using the react hooks

Documentation/application-model/identity.md, Source/ApplicationModel/Applications/Identity/IProvideIdentityDetails.cs, Source/ApplicationModel/Applications/Identity/IdentityDetails.cs, Source/ApplicationModel/Applications/Identity/IdentityProviderEndpointExtensions.cs, Source/ApplicationModel/Tooling/Templates/templates/aspnet/Web/Home.tsx
Normally this would be a major release, but an oversight in designing the API for getting the identity details caused us to miss the fact that we need to know if the user actually is authorized. Since this is actually needed for the flow to work, we decided to not bump the major.
- `IProvideIdentityDetails` is changed to return a structure that holds a property for the actual details and then a property for whether or not the user is authorized.
=> Changing the return object of the IProvideIdentityDetails

Directory.Build.props
- Adding root `README.md` file to the NuGet packages produced.
=> Adding NuGet readme

Source/Kernel/Projections/Engine/IProjection.cs, Source/Kernel/Projections/Engine/Pipelines/ProjectionPipeline.cs, Source/Kernel/Projections/Engine/Projection.cs
- Bug with projections having children - it was assumed the child projection had a key resolver for the parent event, which in most cases it does not.
=> Only use key resolver for child projection if it actually has it

Source/Fundamentals/Json/ExpandoObjectConverter.cs, Source/Fundamentals/Schemas/ReflectionService.cs, Specifications/Fundamentals/Json/for_ExpandoObjectConverter/TargetType.cs, Specifications/Fundamentals/Json/for_ExpandoObjectConverter/when_converting_complex_structure_to_expando_object.cs
- When using Newtonsofts `[JsonConverter(typeof(StringEnumConverter))]`, NJsonSchema would by default treat it as a string value. Changed this behavior and it will now always treat it as an integer.
=> Supporting use of the StringEnumConverter for Newtonsoft for enums

Source/ApplicationModel/Tooling/ProxyGenerator/Templates/Command.hbs
- Fixing a bug in the command template so that enumerable properties actually now gets rendered correctly as JS arrays.
=> Using correct variable; IsEnumerable and not Enumerable

Source/Kernel/Store/MongoDB/Observation/ObserverStorageProvider.cs
A missing consideration in the `ObserverStorageProvider` for observer key was causing Inbox observers for different microservices to reuse its state. Causing strange behavior.
This version is therefor a major release, since it actually is not backwards compatible with the stored observers state for inboxes.
To remedy this, you can change the existing observer in the `observers collection` with the `observerId: 85dc950d-1900-4407-a484-ec1e83da16c6`. In the `_id` field you can append the microserviceId you believe is correct (if you only have one, this should be easy).
The expected format is: 
`<guid> : <guid> : <guid>`
Where the Guid represent:
`<event sequence id> : <observer id> : <source microservice id>`.
Since the two first segments are known it will become: …
=> Changing key for inbox to be correct

Documentation/clients/dotnet/integration/integration.md, Source/Clients/DotNET/Integration/EventToAppend.cs, Source/Clients/DotNET/Integration/EventsToAppend.cs, Source/Clients/DotNET/Integration/ImportBuilderExtensions.cs, Source/Clients/DotNET/Integration/ImportOperations.cs, Specifications/Clients/DotNET/Integration/for_EventsToAppend/when_adding.cs, Specifications/Clients/DotNET/Integration/for_ImportBuilderExtensions/when_appending_event_by_convention.cs, Specifications/Clients/DotNET/Integration/for_ImportBuilderExtensions/when_appending_event_by_convention_with_valid_from.cs, Specifications/Clients/DotNET/Integration/for_ImportBuilderExtensions/when_appending_event_from_callback_with_valid_from.cs, Specifications/Clients/DotNET/Integration/for_ImportOperations/given/all_dependencies_for.cs, Specifications/Clients/DotNET/Integration/for_ImportOperations/when_applying_external_model_with_one_property_changed.cs, Specifications/Clients/DotNET/Integration/for_ImportOperations/when_applying_external_model_with_one_property_changed_for_public_event.cs
- Support for `ValidFrom` for integration adapters as an optional parameter to the `AppendEvent` method.
=> Added support for ValidFrom for integrations

Source/Clients/DotNET/Integration/ImportBuilderExtensions.cs
- `ValidFrom` in callbacks when used in `AppendEvent` with integration adapters are now nullable, as it should be.
=> Forgot that valid from needs to be nullable

Source/Workbench/events/store/EventHistogram.tsx
This is a major release with quite a few changes. Read the changelog carefully for details.
Primarily this release is about paying back some technical debt and fixing some stability issues in the making.
Also a focus on fixing APIs that were wrong, namespaces that were wrong and general consolidation of the codebase for increased maintainability.
- Validation check during proxy generation if return type and query / command name has the same name and in the same namespace / path. Breaks the build.
- Adding [Seq](https://hub.docker.com/r/datalust/seq) as a Serilog Sink. (#393)
- With the introduction of WebSocket as a client, you should consider change set loglevel in `appsettings.json` to `Information` for `Websocket`. Otherwise you'll see the ping/pong going between client and kernel all …
=> Fixing silly mistake - after regen of proxies

Source/Fundamentals/Json/DateOnlyJsonConverter.cs, Specifications/Fundamentals/Fundamentals.csproj, Specifications/Fundamentals/Json/for_DateOnlyJsonConverter/when_converting_from_date_only.cs, Specifications/Fundamentals/Json/for_DateOnlyJsonConverter/when_converting_to_date_only_from_iso_string.cs, Specifications/Fundamentals/Json/for_DateOnlyJsonConverter/when_converting_to_date_only_from_iso_string_from_datetimeoffset.cs, Specifications/Fundamentals/Json/for_DateOnlyJsonConverter/when_converting_to_date_only_from_string.cs
DateOnlyJsonConverter handles dates in ISO 8601 format.  This is the format that a Date object in Javascript will serialize to in JSON.stringify.
- Specs covering more string format
- Implementation of DateOnlyJsonConverter to use TryGetDateTimeOffset and falling back to TryGetDateTime and then just Read.
- DateTime string in JSON that was generated from the JS Date Object in the proxy was not deserialized correctly.  The entire command failed as a consequence.
=> DateOnlyJsonConverter can handle dates in more formats (esp. ISO 8601)

Source/ApplicationModel/Applications/Logging/ExecutionContextLogEnricher.cs, Source/ApplicationModel/Applications/Logging/ExecutionContextLoggingExtensions.cs, Source/ApplicationModel/Applications/Logging/LoggingHostBuilderExtensions.cs, Source/Fundamentals/Execution/ExecutionContextManager.cs, Source/Kernel/Server/README.md
- Adding log enrichment for Serilog to execution context. Automatically hooked up in Application Model. (#445)
Usage:
```csharp
Log.Logger = new LoggerConfiguration()
.Enrich.WithExecutionContext()
.CreateLogger();
```
=> Adding execution context log enricher

Source/ApplicationModel/Tooling/ProxyGenerator/SourceGenerator.cs
- The output folder path for proxy generation was not sanitized and properly resolved to an absolute path, so a relative path of `../Web/API` could end up with a `/your/path/to/the/code//../Web/Api` which then failed getting the correct relative path of a type when outputting types.
=> Sanitizing the output folder path so we get a correct fully qualified path

Source/Kernel/Engines/Projections/Definitions/ProjectionDefinitions.cs
- Projection has changed fixed from doing `.Equals()` on JSON object against a JSON string to both being JSON strings.
=> Checking strings against strings - not string against JSON object

Source/ApplicationModel/Frontend/queries/QueryFor.ts
- Fixed frontend QueryFor to return correct query result with data set to correct default value when errors occur.
=> Return correct no success data for the data type with correct default value

Samples/Banking/Bank/Web/webpack.config.js, Source/ApplicationModel/Frontend/identity/IdentityProvider.tsx
- Fixed the frontend `IdentityContextProvider` to explicitly call the `/.aksio/me` endpoint if no cookie is there. This is to improve the devex. It does however require the `x-ms-client-*` headers to be set for the endpoint to work.
=> For improved devex; add an explicit call to /.aksio/me if no cookie

Source/Clients/DotNET/Observation/IObserversRegistrar.cs, Source/Clients/DotNET/Observation/ObserversRegistrar.cs
- Added missing API for getting an observer CLR type by its observer id.
=> Adding needed API for getting observer CLR type from observer id

Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorage.cs, Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorageLogMessages.cs
- Skip redacting if an event is already redacted. (#796)
=> Fixing so that we don't allow redaction of already redacted events

Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorage.cs, Source/Kernel/Shared/Events/EventType.cs
- `EventType` now supports parsing string representation without generation info, defaulting to `EventGeneration.First` for that scenario.
- When checking if redaction has already happened, we now check only the `Id` part - we don't care about which generation at that point.
=> Supporting parsing of input without generation info

Source/Kernel/Grains/Observation/ObserverSupervisor.Rewinding.cs
- Fixing so that the next event sequence number for observers that gets called with `RewindPartitionTo()` gets set to what it was after it is done.
=> Set the next sequence number to what it was after rewind for a partition.

Source/ApplicationModel/Applications/Applications.csproj
- Added the compact JSON formatter as it was missing as a dependency.
=> Adding the Serilog JSON Compact formatter

Source/ApplicationModel/Applications/Logging/EventIdHash.cs, Source/ApplicationModel/Applications/Logging/RenderedCompactJsonFormatter.cs
- Added custom Serilog formatter for outputting a rendered compact JSON format, yet not as compact as the official one. Based on the official implementation found [here](https://github.com/serilog/serilog-formatting-compact/tree/dev/src/Serilog.Formatting.Compact/Formatting/Compact).
Usage:
```json
{
"Serilog": {
"Using": [
"Serilog.Sinks.Console"
],
"WriteTo": [
{
"Name": "Console",
"Args": {
"formatter": "Aksio.Cratis.Applications.Logging.RenderedCompactJsonFormatter, Aksio.Cratis.Applications"
}
}
]
}
}
```
=> Adding JSON log formatter based on the Serilog Compact Json Formatter

Source/Kernel/Grains.Interfaces/Silos/IDeadSilosScavenger.cs, Source/Kernel/Grains/Silos/BootProcedure.cs, Source/Kernel/Grains/Silos/DeadSilosScavenger.cs, Source/Kernel/Grains/Silos/DeadSilosScavengerLogMessages.cs, Source/Kernel/Grains/Silos/OrleansSiloInfo.cs
- Scavenger job that cleans up dead silos when using Azure Table Store. Fixing #624.
=> Adding a scavenger job to clean up dead silos

Source/Clients/DotNET/Clients/OrleansAzureTableStoreKernelClient.cs, Source/Clients/DotNET/Clients/RestKernelClient.cs
- Adding a `OnKernelUnavaialable()` virtual method for `RestKernelClient` implemented by the `OlreansAzureTableStoreKernelClient` which will refresh silo information before a retry.
=> Adding a mechanism for when kernel becomes unavailable

Source/ApplicationModel/Applications/Identity/IdentityProviderEndpointExtensions.cs
- Fixing so that results from the `.aksio/me` identity details endpoint does not escape JSON result during serialization.
=> Using relaxed Json escaping for identity details result

Source/Clients/DotNET/Clients/RestKernelClient.cs
- Fixing so that the client can call the Kernel API out of execution context. We're for the most part very specific on providing the necessary information on API routes.
=> Making it possible to call the Kernel out of execution context

Source/Kernel/Domain/Observation/Observers.cs, Source/Kernel/Grains/Observation/RecoverFailedPartition.cs, Source/Workbench/API/events/store/observers/RetryPartition.ts, Source/Workbench/eventStore/FailedPartitions.tsx
- Added the capability of retrying a failed partition. This is done by selecting a failed partition in the "failed partitions" view and then clicking the "Retry" button.
=> Adding support for retrying a partition manually

Source/Kernel/MongoDB/Observation/ObserverStateClassMap.cs
- Removing current subscription information from the Observer state being stored, as this has only an in-memory value.
=> Unmap the current subscription information from storage, as this is only for in-memory state

Source/Clients/DotNET/ClientBuilder.cs, Source/Clients/DotNET/Configuration/ClientOptions.cs, Source/Clients/DotNET/Connections/ClusteredKernelClient.cs, Source/Clients/DotNET/Connections/InsideKernelConnection.cs, Source/Clients/DotNET/Connections/OrleansAzureTableStoreKernelConnection.cs, Source/Clients/DotNET/Connections/RestKernelConnection.cs, Source/Clients/DotNET/Connections/SingleKernelConnection.cs, Source/Clients/DotNET/Connections/StaticClusteredKernelConnection.cs, Source/Clients/DotNET/KernelConnectivityClientBuilderExtensions.cs
- The `ClientOptions` type was in the wrong namespace, fixed to be in `Aksio.Cratis.Configuration` as expected.
=> Fixing namespace for ClientOptions

Source/Clients/Specifications/EventSequenceStorageProviderForSpecifications.cs
- Dead lock situation when starting kernel with observers needing to replay. Solved this by explicitly priming the event sequence caches at startup, rather than lazily through the streaming infrastructure.
- Moving the decision of what time an event operation occurred to the owning systems (e.g. EventSequence grain), rather than letting the persistence layer do this.
- Fixing underlying problem with observer state with regards to current subscriptions, causing replays to only work once and sometimes never. 
- Making redaction work in the workbench again by making causation and caused optional and setting these on server side if not set. The endpoints got a 409 with validation error messages before this change.
=> Fixing broken static code analysis rules. Tried to release before checks

Source/Kernel/Domain/EventSequences/AppendEvent.cs, Source/Kernel/Domain/EventSequences/AppendManyEvents.cs
- Making `Causation` and `CausedBy` on the server side optional and automatically injected if not there based on context in the server. This is for backwards compability with any 9.x clients
=> Fixing comments

Source/Kernel/Domain/Observation/Observers.cs
- Client Observer registrations seems to fail under some circumstances and not necessarily for all. This could be linked to an attempt of an optimization of doing a `Task.Run()` for calling the `ClientObservers` grain for registering and returning to the client as soon as possible. This seems to fail sometimes. Taking it out and it seems to be consistent.
=> Removing Task.Run() for registering observers - seems that this is in conflict with Orleans task model

Benchmarks/Benchmarks.csproj
- Setting `IsPackable` to `false` for the Benchmark project - we're not trying to publish this to NuGet.
=> Make benchmark project not packable

Source/Kernel/Grains.Interfaces/Observation/IRecoverFailedPartition.cs, Source/Kernel/Grains/Observation/FailedPartitionSupervisor.cs, Source/Kernel/Grains/Observation/RecoverFailedPartition.cs, Source/Kernel/Shared/Observation/RecoverFailedPartitionState.cs, Specifications/Kernel/Grains/Observation/for_FailedPartitionSupervisor/when_failing_a_partition/and_the_partition_is_already_failed.cs, Specifications/Kernel/Grains/Observation/for_FailedPartitionSupervisor/when_failing_a_partition/and_the_partition_is_not_already_failed.cs, Specifications/Kernel/Grains/Observation/for_RecoverFailedPartition/when_recovering/with_each_event_failing_first_time_then_succeeding.cs, Specifications/Kernel/Grains/Observation/for_RecoverFailedPartition/when_recovering/with_initial_event_failing_first_time_then_succeeding.cs, Specifications/Kernel/Grains/Observation/for_RecoverFailedPartition/when_recovering/with_no_errors_on_processing_from_failed_event.cs, Specifications/Kernel/Grains/Observation/for_RecoverFailedPartitionState/when_initialising_error.cs
Addresses #854 by fixing an issue in the RecoverFailedPartition grain
- When recovery of a failed partition is started the original occurred timestamp is carried over all the way to the state
- Added an additional ResumeRecovery method resumes recovery without overriding the InitialPartitionFailedOn timestamp
=> Initial partition failed

Source/Kernel/MongoDB/Identities/MongoDBIdentityStore.cs
- The resolution of identity for things like caused by looks for a match on subject first and if no subject is registered with that it will try to resolve using the username claim. If already have multiple registred users with subject set to null or empty string, then this would fail on startup. This version fixes this problem.
=> Filtering out identities without subject set for the look up of identity by subject

Directory.Packages.props
- Fixing server crash at startup by upgrading the dependency to `Fundamentals` package, which has a fix for what is classified as assembly referenced packages - avoiding duplicates in type discovery.
=> Upgrading fundamentals

Source/Kernel/Grains/Observation/CatchUp.cs, Source/Kernel/Grains/Observation/Replay.cs
- Fixing `CatchUp` and `Replay` to not write state on the `Stop()` method, as it is not altering any `ObserverState` at that point. This fixes a problem we've seen were observers seem to be observing events multiple times. The reason for this is that the in-memory state representation of the grain is stale. Observer worker jobs share the state with the parent supervisor, but it is not synchronized and only updated when absolutely needed. This whole thing will be ripped out in an upcoming version with a complete rewrite of how observers work.
=> Changing stop to do nothing if there is nothing to stop. + do not write its state - it can be stale

Source/Kernel/Grains.Interfaces/Projections/ImmediateProjectionResult.cs, Source/Kernel/Grains/Projections/ImmediateProjection.cs
- Fixing immediate projections to return empty result if projection doesn't have any events its observing.
=> Fixing so that if there are no event types for an immediate projection, we return empty result

Source/Kernel/Engines/Sinks/InMemory/InMemorySink.cs
- Fixing `InMemorySink` to set the `Id` property to the key value. This fixes a problem when using immediate projections and the read model coming back does not have a `null` for the `Id` property.
=> Putting in the key into the Id property when applying changes

Source/Clients/Specifications/Projections/ProjectionSpecificationContext.cs, Source/Kernel/Engines/Sinks/InMemory/InMemorySink.cs
- `GetById()` on `ProjectionSpecificationContext` now starts with a clean model when calling it. Making it safe to call it multiple times and get the same result.
=> Fixing GetById() to start with a fresh model - so you can call it multiple times safely

Source/Kernel/MongoDB/ExpandoObjectConverter.cs, Specifications/Kernel/MongoDB/for_ExpandoObjectConverter/TargetType.cs, Specifications/Kernel/MongoDB/for_ExpandoObjectConverter/when_converting_complex_structure_to_bson_document.cs, Specifications/Kernel/MongoDB/for_ExpandoObjectConverter/when_converting_complex_structure_to_expando_object.cs
- Fixing BSON to `ExpandoObject` converter to support collections of primitives such as `int` and `string`. It made the items `null` before.
=> Fixing support for array of primitive types as children during conversion

Source/Kernel/MongoDB/EventSequences/EventSequenceQueries.cs, Source/Kernel/MongoDB/EventSequences/MongoDBEventSequenceStorage.cs
- Fixed the EventSequence queries that used `.Value` for the sequence number to be just the actual value. This seems to fix a problem where it tries to add a `Convert()` method to the query, which is not something that can be translated to MongoDB.
=> removing .Value from the GTE/LTE queries. This seems to be wrong

Source/Kernel/MongoDB/Operations/MongoDBRecommendationStorage.cs
- Removing JSON serialization for request object of recommendations, which caused an error since we now serialize it BsonDocument directly.
=> Removing Json serializer options - not needed

Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/given/a_catchup_observer_and_a_request.cs, Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_asking_if_can_resume/and_it_is_not_subscribed.cs, Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_asking_if_can_resume/and_it_is_subscribed.cs, Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_completed.cs, Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_preparing_steps.cs, Specifications/Kernel/Grains/Observation/Jobs/for_CatchUpObserver/when_step_completes.cs, Specifications/Kernel/Grains/Observation/States/for_CatchUp/given/a_catch_up_state.cs, Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_a_catch_up_is_already_running.cs, Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_a_paused_catch_up_job_exists.cs, Specifications/Kernel/Grains/Observation/States/for_CatchUp/when_entering/and_no_jobs_are_running.cs, Specifications/Kernel/Grains/Observation/States/for_Replay/given/a_replay_state.cs, Specifications/Kernel/Grains/Observation/States/for_Replay/when_entering/and_a_paused_replay_job_exists.cs, Specifications/Kernel/Grains/Observation/States/for_Replay/when_entering/and_a_replay_job_is_already_running.cs, Specifications/Kernel/Grains/Observation/States/for_Replay/when_leaving/and_a_replay_job_is_already_running.cs
- Serialization to and from MongoDB fixed for types with `object` properties. These are now getting a discriminator value that makes sense and is possible to get back to the original type. Allowing any types to be considered.
- Internal fallback JSON serialization for Grain communication with support for types with `object` properties.
- Adding metadata to the JSON schema for properties that hold a nullable `ConceptAs<>` type allowing the Kernel to treat these as nullables and not give a default value if the value is indeed null.
=> Fixing compiler errors and broken specs after internal API changes

Source/Kernel/Server/CpuBoundWorkersExtensions.cs, Source/Kernel/Server/Program.cs
- Configuring the CPU bound workers as the first thing, seems to be a timing issue with this not being configured and dependencies to `LimitedConcurrencyLevelTaskScheduler`.
=> Moving configuration of the CPU bound workers

Source/Kernel/Server/CpuBoundWorkersExtensions.cs
- Moved to a concrete singleton instead of a provider that provides the singleton for `LimitedConcurrencyLevelTaskScheduler`.
=> Binding the LimitedConcurrencyLevelTaskScheduler as a Singleton

Source/Kernel/Grains/Workers/CpuBoundWorker.cs
- Lazily getting an instance of the `TaskScheduler` for `CpuBoundWorker` when its needed the first time.
=> Lazily create the task scheduler on first access

Source/Kernel/Grains/EventSequences/EventSequences.cs, Source/Kernel/Grains/EventSequences/EventSequencesLogMessages.cs
- Stopping the rehydration of event sequences from failing at startup, instead log an error. We want the server to survive any non fatal errors at startup.
=> Stopping the rehydrate from failing during startup - but output the error

Source/Kernel/Grains/EventSequences/EventSequences.cs, Source/Kernel/Server/BootProcedure.cs
- Ensuring correct execution context for the different parts of the boot procedure of the Kernel.
=> Ensuring execution context is correct

Source/Workbench/eventStore/Jobs.tsx
- Jobs view now shows `[N/A]` when there is no status changes instead of crashing.
=> If there are no status changes - show [N/A] on start time

Source/Kernel/Read/EventSequences/EventSequence.cs
Minor bugfix.
- Fixes `/api/events/store/{microserviceId}/{tenantId}/sequence/{eventSequenceId}/all` endpoint to have eventTypes actually be optional as it should.
=> Make eventTypes optional, as it should be.

Source/Kernel/Read/EventSequences/EventSequence.cs, Source/Workbench/API/events/store/sequence/GetAppendedEventsRange.ts
Added endpoint necessary for client observers.
- Added `/api/events/store/{microserviceId}/{tenantId}/sequence/{eventSequenceId}/range` endpoint which allow for fetching of events based on event sequence number instead of paging.
=> Add REST endpoint to fetch a defined range of appended events

Source/Clients/DotNET/Projections/IProjectionBuilder.cs, Source/Clients/DotNET/Projections/ProjectionBuilder.cs, Source/Clients/DotNET/Projections/RemovedWithBuilder.cs
- Limiting the API surface for `RemoveWith()` to only what it is capable of and also setting up the correct return type for the inherited `KeyBuilder`.
=> Fixing what gets exposed on the RemoveWith API - so we don't expose more than what is possible

Source/Clients/DotNET/Reactions/Reactors.cs, Source/Kernel/Grains/Observation/Reactions/Clients/ReactorObserverSubscriber.cs, Source/Kernel/Grains/Observation/Reactions/Clients/ReactorObserverSubscriberLogMessages.cs
- Ensure running of Register method only once for Reactors.
- Improve error logging.
Related to: https://github.com/Cratis/Chronicle/issues/1324
Fixes also: https://github.com/Cratis/Chronicle/issues/1411
=> Fix registering of reactors twice

Directory.Build.props, Directory.Packages.props
- Addresses the [vulnerability in System.Text.Json 8.0.0](https://github.com/advisories/GHSA-hh2w-p6rv-4g7w) by setting explicit global version to latest stable 8.0.4
=> set explicit package version 8.0.4

Source/Clients/DotNET/EventSequences/EventSequence.cs
- `EventSourceType` was not set on request to Kernel for appending many, causing `NullReferenceException` during conversion to the `EventSourceTypeId` inside Kernel. This is now fixed.
=> Setting EventSourceType property when appending many for each event

Source/Api/Api.csproj, Source/Api/ApiServiceCollectionExtensions.cs
- Fixing Xml docs used in Swagger to use an embedded file instead of trying to find a physical file on disk that is not there. This caused the Embedded workbench to not load.
=> Embed Xml docs for API into Assembly

Source/Api/Api.XmlDoc.csproj, Source/Api/Api.csproj, Source/Api/Common.props, Source/Api/GlobalUsings.cs
- Fixing Xml docs used in Swagger to use an embedded file instead of trying to find a physical file on disk that is not there. This caused the Embedded workbench to not load.
=> Fixing embedding of XmlDocs

Source/Clients/DotNET.Specs/Transcations/for_UnitOfWork/when_committing/and_then_resetting_and_then_committing.cs, Source/Clients/DotNET.Specs/Transcations/for_UnitOfWork/when_rolling_back/and_then_resetting_and_then_committing.cs, Source/Clients/DotNET/Transactions/IUnitOfWork.cs, Source/Clients/DotNET/Transactions/UnitOfWork.cs
- Added a `Reset()` method on `IUnitOfWork` to be able to reset a unit of work to its initial state.
=> Adding a reset method for a unit of work, to be able to reset to initial state

Source/Kernel/Server/Program.cs, Source/Kernel/Server/Server.csproj
- Due to problems with ReadyToRun compiled version of the server when part of the Docker images, we decided to let the Workbench frontend be within the `wwwroot` folder and served as static files from the root Web server rather than use the Embedded option we provide.
=> Moving away from embedded workbench due to ReadToRun issues with embedded manifests

Integration/Orleans.InProcess/Projections/Scenarios/given/a_projection_and_events_appended_to_it.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/BookAddedToInventory.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/BookBorrowed.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/BorrowedBook.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/BorrowedBooksProjection.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/UserOnboarded.cs, Integration/Orleans.InProcess/Projections/Scenarios/when_projecting_with_join_on_id/and_event_joined_has_happened_first.cs, Source/Kernel/Projections/Pipelines/Steps/SetInitialState.cs, Source/Kernel/Projections/ProjectionFactory.cs
- When using `.Join<>` and then using `.On(m => m.Id)`- the Key/Id of the model, it never resolved the join. This fixes that and considers a join expression on the primary key to be a join expression to use for `ResolveJoin` operation which runs after events have been projected to catch any past events it should resolve properties from.
=> FIxing a problem with projection join that joins on the Id of the model

Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintIndexUpdater/when_updating/and_event_in_context_is_not_part_of_definition.cs, Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintIndexUpdater/when_updating/and_event_in_context_is_part_of_definition.cs, Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintIndexUpdater/when_updating/and_event_in_context_is_remove_event.cs, Source/Kernel/Grains/Events/Constraints/UniqueConstraintDefinitionExtensions.cs, Source/Kernel/Grains/Events/Constraints/UniqueConstraintIndexUpdater.cs
- An exception that occurred when trying to update unique constraint index for events a constraint wasn't defined to handle. This is now fixed by not trying to update the index if the event type is not supported.
=> Making constraint updater ignore events that are not in the definition

Source/Clients/AspNetCore/ChronicleClientServiceCollectionExtensions.cs
- Adding the logger factory for the underlying .NET CronicleClient through its options when using ASP.NET Core setup.
=> Add ILoggerFactory to ChronicleClient options

Directory.Packages.props
- Upgrading to latest Fundamentals that has a fix that caused issues when serializing anything with `CorrelationId` on it. (https://github.com/Cratis/Fundamentals/pull/269)
=> New version of fundamentals with a fix for the CorrelationId concept

Directory.Packages.props, Source/Kernel/Grains/EventSequences/AppendedEventsQueue.cs, Source/Kernel/Grains/EventSequences/AppendedEventsQueues.cs
- Making the AppendedEventsQueues and specific Queue grains live forever, which is the intended behavior as they are there to scale out handling of events.
- Fixing disposal of Queue task in `AppendedEventsQueue` to only dispose if task is completed and will now wait for its completion on disposal.
- FIxing `TaskCompletionSource` for `AppendedEventsQueue` to run continuations asynchronously.
=> Keeping grains alive forever + fixing disposal only if Task is completed

Source/Kernel/Server/Program.cs, Source/Kernel/Storage.MongoDB/MongoDBChronicleBuilderExtensions.cs
- Defaulting the database for MongoDB to the `chronicle+main` database. This means you don't have to specify database when running Orleans InProcess. This will also then be compatible if moving from in-process to out-of-process as it will default to this.
- Adding an overload to `.WithMongoDB()` that takes the `ChronicleOptions` which is then passed along from the Kernel Server program.
=> Making the MongoDB database default to the chronicle one, which is what is expected

Directory.Packages.props, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/given/a_single_subscriber.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/given/two_subscribers.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/multiple_events_with_different_partitions_with_multiple_subscribers_that_subscribes_to_all_event_types.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/multiple_events_with_different_partitions_with_multiple_subscribers_that_subscribes_to_one_event_type_each.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/multiple_events_with_different_partitions_with_single_subscriber.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/single_event_with_single_subscriber.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/with_subscriber_that_has_unsubscribed.cs, Source/Kernel/Grains.Specs/EventSequences/for_AppendedEventsQueue/when_enqueuing/with_subscriber_that_throws_exception_on_first_handle.cs, Source/Kernel/Grains/EventSequences/AppendedEventsQueue.cs, Source/Kernel/Grains/Observation/Observer.cs
Several specs occatioanly failed for appended events queue because it did not take into account parallelism of event sources. However that uncovered other issues in the appended events queue
- Appended events queue issues related to starting too many queue handlers due to incorrect usage of Task.ContinueWith
=> Appended events queue issue and broken specs

Source/Kernel/Concepts/Configuration/ChronicleOptions.cs, Source/Kernel/Concepts/Configuration/Events.cs, Source/Kernel/Grains/EventSequences/AppendedEventsQueues.cs
- Number of appended events queues is now configurable via Kernel configuration, defaults to 8.
=> Making number of queues configurable

Source/Clients/DotNET/EventStore.cs, Source/Clients/DotNET/IEventStore.cs, Source/Clients/DotNET/Observation/FailedPartition.cs, Source/Clients/DotNET/Observation/FailedPartitionAttempt.cs, Source/Clients/DotNET/Observation/FailedPartitionConverters.cs, Source/Clients/DotNET/Observation/FailedPartitionId.cs, Source/Clients/DotNET/Observation/FailedPartitions.cs, Source/Clients/DotNET/Observation/IFailedPartitions.cs, Source/Clients/DotNET/Observation/ObserverId.cs, Source/Clients/DotNET/Observation/Partition.cs, Source/Clients/DotNET/Reactors/IReactors.cs, Source/Clients/DotNET/Reactors/ReactorId.cs, Source/Clients/DotNET/Reactors/Reactors.cs, Source/Clients/DotNET/Reducers/IReducers.cs, Source/Clients/DotNET/Reducers/ReducerId.cs, Source/Clients/DotNET/Reducers/Reducers.cs, Source/Clients/XUnit/Events/EventStoreForTesting.cs
- Addiing an idiomatic C# API for working with failed partitions of observers (Reactors, Reducers, Projections). (#1599)
=> Exposing FailedPartition API as an Idiomatic C# API

Source/Kernel/Grains.Interfaces/Projections/ProjectionChangeset.cs, Source/Kernel/Grains/Projections/ProjectionObserverSubscriber.cs, Source/Kernel/Services/Projections/Projections.cs, Source/Kernel/Setup/ChronicleServerSiloBuilderExtensions.cs
- Internal serialization issue when using `ExpandoObject` in `ProjectionChangeset`. The way we serialize things for Orleans right now, this got basically serialized into Json and deserialized back as ExpandoObject with all properties being `System.Text.Json` node types. Trying to convert from `ExpandoObject` using our converter then messed up everything, especially for objects with arrays - these properties were lost. This should now be fixed.
=> Changing internal payload for projection changes to be JsonObject

Source/Api/Api.csproj
- Fixing the reference to `ResourceEmbedder` to be a private reference and not to be propagated in package dependencies.
=> Making ResourceEmbedder a private reference. It is only used as a tool during build

Source/Workbench/Embedded/ChronicleWorkbenchOptions.cs, Source/Workbench/Embedded/WebServer.cs
- Exposing the ApplicationModel options in the Workbench options.
=> Exposing ApplicationModelOptions to the Workbench and passing it along to the application model

Source/Kernel/Grains/Projections/ProjectionsManager.cs
- Passive Projections are no longer registering subscribers, causing an observer to be allocated (#1766(
=> Disabling observer subscription for passive projections, they are not observing any stream

Source/Workbench/Embedded/WebServer.cs
- Fixing the Embedded Workbench by adding the use of `PathBase` and a middleware for rewriting the Path at the beginning of the pipeline for APIs and all other requests to recognize the base url but be redirected to correct resources which are not necessarily on the base path.
=> Using PathBase to be able to rewrite all input requests

Source/Clients/AspNetCore/ChronicleClientServiceCollectionExtensions.cs, Source/Clients/AspNetCore/ChronicleClientWebApplicationBuilderExtensions.cs, Source/Clients/AspNetCore/Identities/IdentityProvider.cs, Source/Clients/AspNetCore/Identities/IdentityProviderLogging.cs, Source/Clients/DotNET/ChronicleOptions.cs, Source/Clients/Orleans.InProcess/ChronicleClientSiloBuilderExtensions.cs
- Adding the posibility to configure `ChronicleOptions` when adding Chronicle to your `WebApplication`.
- The ASP.NET Core `IdentityProvider` is now hooked up by default, as was expected when using ASP.NET Core and the Orleans InProcess client.
=> Exposing Chronicle configuration options and setting the AspNetCore IdentityProvider as the default identity provider

Source/Clients/DotNET.Specs/Events/Constraints/for_UniqueConstraintDefinition/when_converting_to_contract.cs, Source/Clients/DotNET/Events/Constraints/IUniqueConstraintBuilder.cs, Source/Clients/DotNET/Events/Constraints/UniqueConstraintBuilder.cs, Source/Clients/DotNET/Events/Constraints/UniqueConstraintDefinition.cs, Source/Kernel/Concepts/Events/Constraints/UniqueConstraintDefinition.cs, Source/Kernel/Contracts/Events/Constraints/UniqueConstraintDefinition.cs, Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintValidator/when_validating/and_value_is_allowed.cs, Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintValidator/when_validating/and_value_is_not_allowed.cs, Source/Kernel/Grains.Specs/Events/Constraints/for_UniqueConstraintValidator/when_validating/and_value_returned_for_property_is_null.cs, Source/Kernel/Grains/Events/Constraints/UniqueConstraintValidator.cs, Source/Kernel/Services/Events/Constraints/ConstraintConverters.cs, Source/Kernel/Storage.MongoDB/Events/Constraints/UniqueConstraintsStorage.cs, Source/Kernel/Storage/Events/Constraints/IUniqueConstraintsStorage.cs, Source/Workbench/Web/Api/EventSequences/AppendedEvents.ts
- `.IgnoreCasing()` method for IUniqueConstraintBuilder consumers that allows the user to specify whether or not he cares about case when validating the constraint's uniqueness. (#1723)
=> Allow case ignoring in constraints

.github/workflows/dotnet-build.yml, Integration/Base/GlobalFixture.cs
- Switches to tmpfs for in-memory storage for MongoDB database when running integration specs (#1811)
- Separating out build from running specs and integration specs and using caching of binaries, optimizing builds.
=> Mounting /data/db to Tmpfs - in memory

Source/Workbench/Web/App.tsx
- Putting back the usage of `apiBasePath` this was taken out for debugging purposes and forgotten to put back  🤦🏼
=> Putting back the apiBasePath which was taken out during debugging

Source/Clients/Connections/ServiceCollectionExtensions.cs
- Scoping the logger in `ServiceCollectionExtensions` within `Connections` project to the `ChronicleConnection` and making it an optional service dependency.
=> Scoping ILogger to ChronicleConnection and making it optional
